### ISSUE TITLE
Panic in GAPIS when tracing Vulkan

### ISSUE THREAD

**Issue by tomgoogle** [google/gapid#1311] opened 2017-11-01 18:18 UTC
GAPID Version: 0.9.0:462:128e0d8aced0ec2e82edde156e38fdbe9273f4ee
OS: mac os x x86_64

Tracing a Vulkan application (Triangle or Texture from the [Vulkan examples](https://github.com/googlesamples/android-vulkan-tutorials)) causes a panic in GAPIS immediately.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x52ce773]

goroutine 74 [running]:
github.com/google/gapid/core/app/crash.Crash.func1()
	/tmpfs/src/github/src/github.com/google/gapid/core/app/crash/crash.go:73 +0x115
sync.(*Once).Do(0x7563470, 0xc42079ae68)
	/tmpfs/src/go/src/sync/once.go:44 +0xbe
github.com/google/gapid/core/app/crash.Crash(0x5cc0dc0, 0x74d4a00)
	/tmpfs/src/github/src/github.com/google/gapid/core/app/crash/crash.go:74 +0x9c
github.com/google/gapid/core/app/crash.handler()
	/tmpfs/src/github/src/github.com/google/gapid/core/app/crash/crash.go:48 +0x52
panic(0x5cc0dc0, 0x74d4a00)
	/tmpfs/src/go/src/runtime/panic.go:489 +0x2cf
github.com/google/gapid/gapis/api/vulkan.(*VkGetPhysicalDeviceMemoryProperties).Mutate(0xc4203eb140, 0x7452720, 0xc420558630, 0xaf, 0xc420a025a0, 0xc4202e3c20, 0x0, 0x0)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/api/vulkan/mutate.go:3729 +0x393
github.com/google/gapid/gapis/replay.(*adapter).MutateAndWrite(0xc4209fa650, 0x7452720, 0xc420558630, 0xaf, 0x748aa80, 0xc4203eb140)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/replay/batch.go:191 +0xcf
github.com/google/gapid/gapis/api/vulkan.(*destroyResourcesAtEOS).Transform(0x75633d8, 0x7452720, 0xc420558630, 0xaf, 0x748aa80, 0xc4203eb140, 0x74292e0, 0xc4209fa650)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/api/vulkan/replay.go:396 +0x63
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc420a025a0, 0x7429160, 0x75633d8, 0x74292e0, 0xc4209fa650, 0x7452720, 0xc420558630, 0xaf, 0x748aa80, 0xc4203eb140)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/api/transform/transforms.go:98 +0x83
github.com/google/gapid/gapis/api/transform.(*TransformWriter).MutateAndWrite(0xc42058efc0, 0x7452720, 0xc420558630, 0xaf, 0x748aa80, 0xc4203eb140)
	<autogenerated>:13 +0xa1
github.com/google/gapid/gapis/api/transform.(*Injector).Transform(0xc4203ce0c8, 0x7452720, 0xc420558630, 0xaf, 0x748aa80, 0xc4203eb140, 0x742b4e0, 0xc42058efc0)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/api/transform/injector.go:39 +0x73
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc420a025a0, 0x74290e0, 0xc4203ce0c8, 0x742b4e0, 0xc42058efc0, 0x7452720, 0xc420558630, 0xaf, 0x748aa80, 0xc4203eb140)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/api/transform/transforms.go:98 +0x83
github.com/google/gapid/gapis/api/transform.(*TransformWriter).MutateAndWrite(0xc42058eff0, 0x7452720, 0xc420558630, 0xaf, 0x748aa80, 0xc4203eb140)
	<autogenerated>:13 +0xa1
github.com/google/gapid/gapis/api/vulkan.(*readFramebuffer).Transform.func1()
	/tmpfs/src/github/src/github.com/google/gapid/gapis/api/vulkan/read_framebuffer.go:50 +0x5c
github.com/google/gapid/gapis/api/vulkan.(*readFramebuffer).Transform(0xc4203ce0c0, 0x7452720, 0xc420558630, 0xaf, 0x748aa80, 0xc4203eb140, 0x742b4e0, 0xc42058eff0)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/api/vulkan/read_framebuffer.go:54 +0x2ea
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc420a025a0, 0x7429220, 0xc4203ce0c0, 0x742b4e0, 0xc42058eff0, 0x7452720, 0xc420558630, 0xaf, 0x748aa80, 0xc4203eb140)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/api/transform/transforms.go:98 +0x83
github.com/google/gapid/gapis/api/transform.(*TransformWriter).MutateAndWrite(0xc42058f020, 0x7452720, 0xc420558630, 0xaf, 0x748aa80, 0xc4203eb140)
	<autogenerated>:13 +0xa1
github.com/google/gapid/gapis/api/vulkan.(*VulkanTerminator).Transform(0xc420558a80, 0x7452720, 0xc420558630, 0xaf, 0x748aa80, 0xc4203eb140, 0x742b4e0, 0xc42058f020)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/api/vulkan/vulkan_terminator.go:436 +0x31d
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc420a025a0, 0x7429120, 0xc420558a80, 0x742b4e0, 0xc42058f020, 0x7452720, 0xc420558630, 0xaf, 0x748aa80, 0xc4203eb140)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/api/transform/transforms.go:98 +0x83
github.com/google/gapid/gapis/api/transform.(*TransformWriter).MutateAndWrite(0xc42058f050, 0x7452720, 0xc420558630, 0xaf, 0x748aa80, 0xc4203eb140)
	<autogenerated>:13 +0xa1
github.com/google/gapid/gapis/api/vulkan.(*makeAttachementReadable).Transform(0xc4205589f0, 0x7452720, 0xc420558630, 0xaf, 0x748aa80, 0xc4203eb140, 0x742b4e0, 0xc42058f050)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/api/vulkan/replay.go:385 +0x1151
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc420a025a0, 0x74291e0, 0xc4205589f0, 0x742b4e0, 0xc42058f050, 0x7452720, 0xc420558630, 0xaf, 0x748aa80, 0xc4203eb140)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/api/transform/transforms.go:98 +0x83
github.com/google/gapid/gapis/api/transform.(*TransformWriter).MutateAndWrite(0xc42058f080, 0x7452720, 0xc420558630, 0xaf, 0x748aa80, 0xc4203eb140)
	<autogenerated>:13 +0xa1
github.com/google/gapid/gapis/api/transform.(*DCE).Flush(0xc42058ecf0, 0x7452720, 0xc420558630, 0x742b4e0, 0xc42058f080)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/api/transform/dce.go:156 +0x864
github.com/google/gapid/gapis/api/transform.Transforms.Transform(0xc4207f9a00, 0x6, 0x8, 0x7452720, 0xc420558630, 0xc42032dd08, 0x0, 0x0, 0x74292e0, 0xc4209fa650)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/api/transform/transforms.go:44 +0x32c
github.com/google/gapid/gapis/api/vulkan.API.Replay(0x7452720, 0xc420558630, 0xc4203ce0b0, 0xc4203ce0b8, 0x5e80080, 0xc420a22c90, 0xc4208900f0, 0xa, 0xa, 0xc4202ee2a0, ...)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/api/vulkan/replay.go:659 +0xe1d
github.com/google/gapid/gapis/api/vulkan.(*API).Replay(0x75633d8, 0x7452720, 0xc420558630, 0xc4203ce0b0, 0xc4203ce0b8, 0x5e80080, 0xc420a22c90, 0xc4208900f0, 0xa, 0xa, ...)
	<autogenerated>:11155 +0xfb
github.com/google/gapid/gapis/replay.(*Manager).execute.func1()
	/tmpfs/src/github/src/github.com/google/gapid/gapis/replay/batch.go:135 +0x18c
github.com/google/gapid/core/app/benchmark.(*DurationCounter).Time(0xc4201b87c0, 0xc42032e398)
	/tmpfs/src/github/src/github.com/google/gapid/core/app/benchmark/counter.go:163 +0x7b
github.com/google/gapid/gapis/replay.(*Manager).execute(0xc4202fa0a0, 0x7452720, 0xc420558630, 0x93d358f55f0fe0a0, 0x9bfc4512da2f4967, 0x911358a55bd5de2, 0x26587dc64a305908, 0x8faadab5f4b8d470, 0x5e80080, 0xc420a22c90, ...)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/replay/batch.go:136 +0xa33
github.com/google/gapid/gapis/replay.(*Manager).batch(0xc4202fa0a0, 0x7452720, 0xc4205583f0, 0xc420858140, 0xa, 0xa, 0x5de06c0, 0xc4209f4568, 0x5e84dc0, 0xc420576410, ...)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/replay/batch.go:68 +0x514
github.com/google/gapid/gapis/replay.(*Manager).(github.com/google/gapid/gapis/replay.batch)-fm(0x7452720, 0xc4204d4c00, 0xc420858140, 0xa, 0xa, 0x5de06c0, 0xc4209f4568, 0x5e84dc0, 0xc420576410, 0x1)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/replay/manager.go:126 +0x93
github.com/google/gapid/gapis/replay/scheduler.(*bin).exec(0xc420092200, 0x7452720, 0xc4204d4c00, 0xc42018d320)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/replay/scheduler/scheduler.go:243 +0x2d8
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run(0xc4203bd360, 0x7452720, 0xc4204d4c00)
	/tmpfs/src/github/src/github.com/google/gapid/gapis/replay/scheduler/scheduler.go:176 +0x469
github.com/google/gapid/gapis/replay/scheduler.New.func1()
	/tmpfs/src/github/src/github.com/google/gapid/gapis/replay/scheduler/scheduler.go:73 +0x3c
github.com/google/gapid/core/app/crash.Go.func1(0xc4203bd380)
	/tmpfs/src/github/src/github.com/google/gapid/core/app/crash/crash.go:57 +0x43
created by github.com/google/gapid/core/app/crash.Go
	/tmpfs/src/github/src/github.com/google/gapid/core/app/crash/crash.go:58 +0x3f
```
Extra details from the logs and the trace file would be extra helpful.

**Comment by Qining** [comment] 2017-11-01 19:04
hmm, looks like a crash during replay. Is there a generated trace? Is the app running on desktop or Android?

**Comment by Qining** [comment] 2017-11-01 19:04
hmm, looks like a crash during replay. Is there a generated trace? Is the app running on desktop or Android?

**Comment by tomgoogle** [comment] 2017-11-01 19:07
App is running on Android. Sent you a trace offline!

**Comment by Qining** [comment] 2017-11-01 21:48
The reason is already found. It is in the code to handle 'multiple GPUs' case (returned order may be different in trace and replay). Currently gapid only works when `vkGetPhysicalDeviceProperties` is the first command using `VkPhysicalDevice`. But in the sample, `vkGetPhysicalDeviceMemoryProperties` is called and `vkGetPhysicalDeviceProperties` is never called.

I'm working on a solution now, it might be a little bit tricky, as we now rely on VenderID and DeviceID to differentiate GPUs, and such info is contained in `VkPhysicalDeviceProperties`.

**Comment by ben-clayton** [comment] 2017-11-02 11:25
Do we know if this is a regression from the last public release we made?
I was hoping to get 0.9 out today - if this has been introduced since the last public release, we should consider reverting the offending change.

**Comment by Qining** [comment] 2017-11-02 13:03
A fix will be done within 30 mins

**Comment by Qining** [comment] 2017-11-02 13:50
The CL causing the problem is #1165 .

**Comment by Qining** [comment] 2017-11-02 13:59
But even with #1320, the `Texture` sample still shows wrong result for Mid-Execution Capture. Full trace works

**Comment by Qining** [comment] 2017-11-02 14:17
Actually, the problem is in the sample side. In the sixth sample: `Texture`, the texture image's layout is `VK_IMAGE_LAYOUT_UNDEFINED` when the app copies data into it and uses the data later for rendering. This is invalid, and so during the image recreation (for MEC), the image data is skipped. So no texture data will be there in the replay side.

I think this behavior is actually right for our debugger, we actually found a bug in the sample code

**Comment by ben-clayton** [comment] 2017-11-02 22:32
@Qining - is the crash fixed? If so, can we close this?
If there are other minor issues that need addressing, please can we open another bug?

**Comment by Qining** [comment] 2017-11-02 22:35
Yes this should have been fixed, but I can not close this issue from my side. Seem like I don't have the permission.

**Comment by ben-clayton** [comment] 2017-11-02 22:37
This is because of the release lockdown. Github's permission systems are not very granular. 
Thanks for the info!

**Closed by ben-clayton** 2017-11-02 22:37 UTC
Labels: GAPIS, P1, Vulkan
