### ISSUE TITLE
Always Fail on Capture Trace: -> getClassLoader() -> <gapit> Main failed

### ISSUE THREAD

**Issue by SenonLi** [google/gapid#153] opened 2017-03-27 22:32 UTC
Dear GAPID,

I am trying Capture Trace using GAPIC, on Windows 7 system Android 7.0, NDK_r13, two different models with all various possible applications I could find.

Whenever I try on Capture Trace, gapit will always fail at the step of "Main", and never pass the line below:
><gapit> Waiting for connection to localhost:50559...

And inside the logcat, not one single GL function could be intercepted:
>03-28 05:43:16.597  7424  7424 E GAPID   : installer.cpp:171 : Couldn't intercept function glVertexPointerBounds at 0x7532c9b8e4

Then a messagebox will fleet on the phone screen for 1s showing that the application (e.x. "Clock") is waiting for the debugger to attach; then the application will crash along with the failure of Capture Trace.

Here below shows the detailed info about how I failed during Capture Trace for every applications:
> 21:47:01.108 I: [start] <gapit> Waiting for ApplicationLoaders.getClassLoader() (abi: arm64-v8a, activity: com.android.deskclock.AlarmsMainActivity, jdwpPort: 50584, on: com.android.deskclock, pid: 7913, port: 50559)
21:47:03.204 I: <gapit> Creating file 'D:\Downloads\GoPath\ReleaseGAPIC_TraceOutput\deskclock_20170327_1446.gfxtrace'
21:47:03.208 I: <gapit> Waiting for connection to localhost:50559...
Press enter to stop capturing...
21:47:03.378 F: <gapit> Main failed
Error: Header send failed
   Cause: write tcp 127.0.0.1:50588->127.0.0.1:50559: wsasend: An established connection was aborted by the software in your host machine.
Tracing failed:
java.lang.Exception: gapit has exited
	at com.google.gapid.server.ChildProcess.runProcess(ChildProcess.java:95)
	at com.google.gapid.server.ChildProcess$1.run(ChildProcess.java:66)

Could anyone help me at least pass getClassLoader() function successfully?

Thank you all in advance! 
Appreciate it!

**Comment by ben-clayton** [comment] 2017-03-27 23:21
`glVertexPointerBounds` is actually one of the few commands that we expect to see this message for. 
Are there others that don't end in `Bounds`? The really valuable bit for us would be a crash with stack trace or an assert message.

**Comment by SenonLi** [comment] 2017-03-28 00:02
Dear Ben-Clayton,

Like what I said, all (more than one thousand) of the gl** functions are failed to be intercepted, all (again, more than one thousand) like below:

>03-28 05:43:14.222   465   813 E BufferQueueProducer: [com.huawei.android.launcher/com.huawei.android.launcher.unihome.UniHomeLauncher] connect: already connected (cur=1 req=1)
03-28 05:43:14.502   506  1291 E bdatd   : [UidStat.cpp] setUidCputime# Invalid delta time, uid: 10056
03-28 05:43:14.580  1037  2769 E HsmCoreServiceImpl: onTransact in code is: 103
03-28 05:43:16.597  7424  7424 E GAPID   : installer.cpp:171 : Couldn't intercept function glVertexPointerBounds at 0x7532c9b8e4
03-28 05:43:16.597  7424  7424 E GAPID   : installer.cpp:171 : Couldn't intercept function glTexCoordPointerBounds at 0x7532c9b8b0
03-28 05:43:16.597  7424  7424 E GAPID   : installer.cpp:171 : Couldn't intercept function glNormalPointerBounds at 0x7532c9b860
03-28 05:43:16.597  7424  7424 E GAPID   : installer.cpp:171 : Couldn't intercept function glColorPointerBounds at 0x7532c9b77c
03-28 05:43:16.597  7424  7424 E GAPID   : installer.cpp:171 : Couldn't intercept function glVertexPointer at 0x7532c9b8e0
03-28 05:43:16.597  7424  7424 E GAPID   : installer.cpp:171 : Couldn't intercept function glTranslatex at 0x7532c9b8dc
03-28 05:43:16.597  7424  7424 E GAPID   : installer.cpp:171 : Couldn't intercept function glTranslatef at 0x7532c9b734
03-28 05:43:16.597  7424  7424 E GAPID   : installer.cpp:171 : Couldn't intercept function glTexParameterxv at 0x7532c9b8d4
03-28 05:43:16.597  7424  7424 E GAPID   : installer.cpp:171 : Couldn't intercept function glTexParameterx at 0x7532c9b8cc
...
...
...

**Comment by ben-clayton** [comment] 2017-03-28 10:14
Hi @SenonLi,
Were there no `Interceptor error:` messages generated?

Based on #133, I assume the device you are using is the [Huawei Mate 9](http://consumer.huawei.com/en/mobile-phones/mate9/index.htm). Is this correct?
Unfortunately I do not believe we have this device in the office. Are you aware of any other device that exhibit similar behavior?

**Comment by ben-clayton** [comment] 2017-03-28 10:22
@SenonLi would you be happy to share the full logcat file with me? There might be something hidden in there that can help me diagnose the issue. My email address is bclayton@google.com.

**Comment by SenonLi** [comment] 2017-03-28 16:43
@ben-clayton Thank you so much, Ben!
I have sent you the full logcat file to your email.

One more question, I was trying to trace a 32bit small test program on the phone, however, could not find it using GAPID. Could you please let me know how to select an Action based on PID when trying to do Capture Trace?

Thank you very much!

**Comment by ben-clayton** [comment] 2017-03-29 16:12
So the underlying issue that's breaking things here is:

```
03-29 00:16:38.824  7585  7585 E GAPID   : installer.cpp:171 : Couldn't intercept function glGetActiveUniform at 0x75335daffc
03-29 00:16:38.824  7585  7585 W GAPID   : installer.cpp:115 : Interceptor error: Intercepting function at 0x7531f8b264 failed: End of function reached after 4 byte when rewriting 12 bytes
```

The interceptor works by patching the start of each driver function to jump to our code. An absolute jump requires a certain number of bytes (8 or 12), which these functions apparently do not have.

I'm going to have to investigate the instructions used by these drivers. I'll contact you privately about trying to solve this.

> Could you please let me know how to select an Action based on PID when trying to do Capture Trace?

GAPID currently requires you to launch the application and cannot attach after the process has already started. I'm not sure there's any way to figure out what intent triggered a process to start.

**Comment by ben-clayton** [comment] 2017-05-19 18:40
Duplicate of #355

**Closed by ben-clayton** 2017-05-19 18:40 UTC
