### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by zjhongxian** [google/gapid#2769] opened 2019-05-24 14:47 UTC
GAPID Version: 1.4.0:5f4620616cbea20dca03ecf0ea29dfcd824114e3
OS: windows 10 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by zjhongxian** [comment] 2019-05-24 14:47
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x8ed31d]

goroutine 133 [running]:
github.com/google/gapid/core/app/crash.Crash(0x528ca40, 0x441d3b0)
	core/app/crash/crash.go:89 +0xae
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x59
panic(0x528ca40, 0x441d3b0)
	GOROOT/src/runtime/panic.go:513 +0x1c7
github.com/google/gapid/gapir/client.(*Connection).Shutdown(0x0, 0x62f1760, 0xc001b1a510, 0x0, 0x0)
	gapir/client/connection.go:117 +0x2d
github.com/google/gapid/gapir/client.(*session).close(0xc0010dd590, 0x62f1760, 0xc001b1a510)
	gapir/client/session.go:377 +0x4e
github.com/google/gapid/gapir/client.(*session).init(0xc0010dd590, 0x62f1760, 0xc001b1a510, 0x6338be0, 0xc0000ec400, 0xc0000f41c0, 0x0, 0x0, 0x0, 0x0, ...)
	gapir/client/session.go:80 +0x242
github.com/google/gapid/gapir/client.(*Client).Connect(0xc000124020, 0x62f1760, 0xc001b1a510, 0x6338be0, 0xc0000ec400, 0xc0000f41c0, 0x0, 0x0, 0x0)
	gapir/client/client.go:66 +0x27d
github.com/google/gapid/gapis/replay.(*manager).connect(0xc0002200e0, 0x62f1760, 0xc001b1a450, 0x6338be0, 0xc0000ec400, 0xc0000f41c0, 0x0, 0x0, 0x0)
	gapis/replay/replay_connection.go:180 +0x220
github.com/google/gapid/gapis/replay.(*manager).execute(0xc0002200e0, 0x62f1760, 0xc001b1a450, 0x6338be0, 0xc0000ec400, 0x14f82b8f312690d8, 0xf9b6b0cf1d6ea425, 0xc6dd972ec41b5d09, 0x34643a1cb7d27aa1, 0x931b0e2cdde57083, ...)
	gapis/replay/batch.go:270 +0x861
github.com/google/gapid/gapis/replay.(*manager).batch.func1(0x6338be0, 0xc0000ec400, 0xc000de6460, 0xb7d27aa1c6dd972e, 0xdde5708334643a1c, 0x312690d8931b0e2c, 0x1d6ea42514f82b8f, 0xc41b5d09f9b6b0cf, 0x528a100, 0xadbea90, ...)
	gapis/replay/batch.go:86 +0x425
github.com/google/gapid/gapis/replay.(*manager).batch(0xc0002200e0, 0x62f1760, 0xc001b1a0f0, 0xc000932000, 0x1, 0x1, 0x57ba640, 0x61f78d8, 0x57e75a0, 0xc001a9a690, ...)
	gapis/replay/batch.go:87 +0x447
github.com/google/gapid/gapis/replay.(*manager).batch-fm(0x62f1760, 0xc000206390, 0xc000932000, 0x1, 0x1, 0x57ba640, 0x61f78d8, 0x57e75a0, 0xc001a9a690, 0x0)
	gapis/replay/manager.go:146 +0x94
github.com/google/gapid/gapis/replay/scheduler.(*bin).exec(0xc0001ce980, 0x62f1760, 0xc000206390, 0xc0002180a0)
	gapis/replay/scheduler/scheduler.go:247 +0x278
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run(0xc0000056c0, 0x62f1760, 0xc000206390)
	gapis/replay/scheduler/scheduler.go:180 +0x440
github.com/google/gapid/gapis/replay/scheduler.New.func1()
	gapis/replay/scheduler/scheduler.go:74 +0x43
github.com/google/gapid/core/app/crash.Go.func1(0xc0000056e0)
	core/app/crash/crash.go:65 +0x4a
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x46

**Comment by pmuetschard** [comment] 2019-05-31 01:09
This is a duplicate of #2620.
And fixed in #2669

**Closed by pmuetschard** 2019-05-31 01:09 UTC
