### ISSUE TITLE
Failed to connect to the application: Only on Unity Android App on PIXEL Device

### ISSUE THREAD

**Issue by WissamElkadi** [google/gapid#1581] opened 2018-02-01 11:29 UTC
I'm trying to capture the tarce of unity app on PIXEL device  and I got this message
 
Failed to connect to the application: read tcp 127.0.0.1:55316->127.0.0.1:55266: wsarecv: An existing connection was forcibly closed by the remote host.. Retrying...

Error: Connecting to JDWP
   Cause: read tcp 127.0.0.1:55316->127.0.0.1:55266: wsarecv: An existing connection was forcibly closed by the remote host.

NOTE:
Android studio is closed.
If I tried Non unity app , It work and I can capture the traces

**Comment by WissamElkadi** [comment] 2018-02-01 13:01
Update : this problem Happen Also Only if I tried to use gradle build system.
If I used Internal is work

**Comment by ben-clayton** [comment] 2018-02-01 13:37
Hi @WissamElkadi,

I'm sorry you're having issues. When you get the `An existing connection was forcibly closed by the remote host.` message, is there anything in logcat suggesting that the application is crashing?

> Update : this problem Happen Also Only if I tried to use gradle build system.

If I understand you correctly, you're saying that when you build your application without using gradle, you are able to successfully trace it?

**Comment by WissamElkadi** [comment] 2018-02-01 13:50
In unity there is 2 options to build android app, one is Internal, antoher is gradle

**Comment by ben-clayton** [comment] 2018-02-06 12:27
Hi @WissamElkadi,

Would it be possible for you to share with me a simple test app that reproduces this issue?
There's no obvious reason to me (without being more hands-on) why on build would work and the other would fail.

Many thanks,
Ben

**Comment by WissamElkadi** [comment] 2018-02-06 13:33
Hi @ben-clayton ,
This is the sample test gradle build apk
https://drive.google.com/open?id=1XGRGVMBnPoUZvNOaGek-CpR3vPfMEaEk
packageId : = com.wissam.tst.gradle

this is the sample test internal build apk
https://drive.google.com/open?id=1tBluE6sr4p701Xm5q8V1G4iP3xRi-5IG
packageId : =  com.wissam.tst.internal

Cheers,
Wissam

**Comment by ben-clayton** [comment] 2018-02-07 13:29
Hi @WissamElkadi,

I'm able to successfully trace and replay both APKs on my device. Maybe the issue is with the Android build? If you can please let me know the build version on your device, I'll reflash to the same and try again.

Cheers,
Ben

**Comment by WissamElkadi** [comment] 2018-02-07 14:43
Hi @ben-clayton,
I just use the current release Ver 1.0.2

Cheers,
Wissam

**Comment by ben-clayton** [comment] 2018-02-07 15:04
@WissamElkadi - please can you paste the output of `adb shell getprop ro.build.fingerprint` ?

**Comment by WissamElkadi** [comment] 2018-02-08 11:20
Hi @ben-clayton, 
You are right both of the links above are working, it is my fault sorry for that.
I think I got the problem's reason, I have tried to make another test which is pretty similar to my failed one, I have enabled Vuforia external SDK, and it is failed only in gradle, so I guess Vuforia disable debugging in gradle build only which make GAPID couldn't connect,  and here is the link.

https://drive.google.com/open?id=1yWLbKF_IUkNwJRuj3-MzFwj0hKDC7CfQ

regarding the adb shell getprop ro.build.fingerprint command it print ==> 
google/marlin/marlin:8.1.0/OPM1.171019.012/4470837:user/release-keys

Cheers,
Wissam

**Comment by AWoloszyn** [comment] 2018-10-30 18:14
IT looks like the APK was built without debugging enabled. Please re-open if this is not the case.

**Closed by AWoloszyn** 2018-10-30 18:14 UTC
Labels: GAPII, P2
