### ISSUE TITLE
GAPID Fails to Capture Trace with ANGLE Enabled

### ISSUE THREAD

**Issue by timvpGoogle** [google/gapid#2754] opened 2019-05-15 18:05 UTC
ToT GAPID (locally built)
Android Q
Pixel 3

Capturing a trace for an APK that's using ANGLE fails. It appears to launch the app, but then GAPID is only able to get a very small amount of data before the app is killed. Some apps crash in `/system/lib64/libhwui.so`, but most others just appear to stop running.

GAPID logs
[gapic.angle.log](https://github.com/google/gapid/files/3183890/gapic.angle.log)
[gapis.angle.log](https://github.com/google/gapid/files/3183891/gapis.angle.log)

Android Logcat
[logcat.gapid.angle.15May2019.txt](https://github.com/google/gapid/files/3183894/logcat.gapid.angle.15May2019.txt)

**Comment by cnorthrop** [comment] 2019-05-15 22:11
From conversations, the app in question traced fine without ANGLE.  So there are two new Android Q things in play here:
- ANGLE in use as the vendor GLES driver
- GAPID loaded as a GLES layer

There must be some new interaction that's falling over.

@pmuetschard I'll work with you to get some more output, root cause the issue.

**Comment by pmuetschard** [comment] 2019-05-31 01:15
Update from our little debugging session:
When the app makes it's first EGL/GL call and the GAPID layer is invoked, we create our "spy". The spy then waits for a connection from the host and once established exchanges some information: the host sends some requested trace flags and the spy sends back the trace header which includes some basic device info. The spy launches a new thread to gather the device info, which includes creating a new GL context. ANGLE appears to deadlock when this new thread calls `eglInitialize`. Removing the device info gathering from the spy allowed GAPID to trace an ANGLE'd app.

Note: the `eglInitialize` and any other EGL/GL calls made when gathering the device info, are invoked directly on the layer beneath us, that is, by resolving the functions using the "get next layer proc address" pointer passed into our layer.

**Comment by AWoloszyn** [comment] 2019-06-12 16:50
This appears to be an issue within ANGLE, closing for now

**Closed by AWoloszyn** 2019-06-12 16:50 UTC
