### ISSUE TITLE
GAPID can't find my phone after building it from source with debug option

### ISSUE THREAD

**Issue by Zhang-Yun** [google/gapid#2814] opened 2019-06-06 07:34 UTC
I am new to GAPID.
I have download source from master and build GAPID from it with debug option selected,but it can't detect my device(xiaomi 8),it shows another device:
![image](https://user-images.githubusercontent.com/4598292/59014771-f2564c00-886f-11e9-9a85-f2c5aa825f5f.png)

and if I try to select app in device to debug ,it shows as following
![image](https://user-images.githubusercontent.com/4598292/59015545-d18ef600-8871-11e9-9a66-0dbde904572b.png)
even I remove gapid in my device ,it still shows me that. 

the weird thing is that when I launch the GAPID downloaded from official Github website,it do detect my phone correctly.as it shows as following:
![image](https://user-images.githubusercontent.com/4598292/59014903-54af4c80-8870-11e9-9edc-d6d1e8f62008.png)

How to fix it so GAPID built from source can detect my device? is there anything I need to config after/before building the GAPID from source

**Comment by AWoloszyn** [comment] 2019-06-06 17:58
There is typically nothing you should have to change. Our last release was a little while ago, so there could have been a regression in the mean-time. When you open GAPID, is there anything interesting in your ADB logcat? or the gapis.log.

**Comment by AWoloszyn** [comment] 2019-06-24 20:15
Alternatively, what options did you provide to GAPID when you built it. This looks like possibly the .apks did not get built.
Did you build with the --config=nodroid option? If so this would mean the .apks are not created.

**Comment by AWoloszyn** [comment] 2019-08-21 16:43
If you have any more info please add it. Closing this for now.

**Closed by AWoloszyn** 2019-08-21 16:43 UTC
