### ISSUE TITLE
Unhandled exception in the UI thread.

### ISSUE THREAD

**Issue by zwcloud** [google/gapid#3343] opened 2019-11-02 11:01 UTC
GAPID Version: 1.7.0:dev-2110Mon-b198af2dc0ae304eb7531ad2e23ff570ae2ead9e
OS: windows 10 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

steps that led to the error: open gapic.exe

> org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
> 	at org.eclipse.swt.SWT.error(SWT.java:4595)
> 	at org.eclipse.swt.SWT.error(SWT.java:4510)
> 	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:188)
> 	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3933)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3564)
> 	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
> 	at org.eclipse.jface.window.Window.open(Window.java:797)
> 	at com.google.gapid.Main$UI.show(Main.java:120)
> 	at com.google.gapid.Main.main(Main.java:69)
> Caused by: java.lang.NullPointerException
> 	at com.google.gapid.LoadingScreen.showOptions(LoadingScreen.java:115)
> 	at com.google.gapid.MainWindow.updateLoadingScreen(MainWindow.java:101)
> 	at com.google.gapid.Main$UI.uiStartup(Main.java:161)
> 	at com.google.gapid.Main$UI.lambda$scheduleIfStillOpen$5(Main.java:183)
> 	at com.google.gapid.widgets.Widgets.ifNotDisposed(Widgets.java:125)
> 	at com.google.gapid.widgets.Widgets.lambda$scheduleIfNotDisposed$1(Widgets.java:153)
> 	at com.google.gapid.widgets.Widgets.lambda$schedule$0(Widgets.java:145)
> 	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
> 	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
> 	... 6 more
> 

gapic.log:

> I20191102-185940082[pool-1-thread-1][server.GapiPaths.checkForTools] Looking for GAPID in C:\Program Files (x86)\gapid -> C:\Program Files (x86)\gapid\gapis.exe
> I20191102-185940102[server.ChildProcess-gapis][server.ChildProcess.runProcess] Starting gapis as [C:\Program Files (x86)\gapid\gapis.exe, -enable-local-files, -crashreport, -analytics, e26e0def-b757-4ea1-9842-31bad138a89c, -log-file, C:\Users\ADMINI~1\AppData\Local\Temp\gapis.log, -log-level, Info, -gapir-args, --log C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\gapir.log --log-level I, --strings, C:\Program Files (x86)\gapid\strings, --gapis-auth-token, B1XQpBq5, --idle-timeout, 60000ms, --adb, C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe]
> I20191102-185940167[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$0] gapis: 10:59:40.167 I: <gapis> Logging to: C:\Users\ADMINI~1\AppData\Local\Temp\gapis.log
> I20191102-185940701[server.ChildProcess$LoggingStringHandler][server.ChildProcess$LoggingStringHandler.lambda$new$0] gapis: Bound on port '51178'
> I20191102-185940701[server.ChildProcess$LoggingStringHandler][server.GapisProcess.lambda$createStdoutHandler$2] Detected gapis startup on port 51178
> I20191102-185940703[pool-1-thread-2][server.GapisProcess.lambda$new$1] Established a new client connection to 51178
> I20191102-185940925[pool-1-thread-1][Server.fetchServerInfo] Server info: name: "DESKTOP-JGHUM2Q" version_major: 1 version_minor: 7 server_local_device { ID { data: 167feebf27db1f1cfe725192f0b8c78728f0e408 } }
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] Unhandled exception in the UI thread.
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	at org.eclipse.swt.SWT.error(SWT.java:4595)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	at org.eclipse.swt.SWT.error(SWT.java:4510)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:188)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3933)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3564)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	at org.eclipse.jface.window.Window.open(Window.java:797)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	at com.google.gapid.Main$UI.show(Main.java:120)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	at com.google.gapid.Main.main(Main.java:69)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] Caused by: java.lang.NullPointerException
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	at com.google.gapid.LoadingScreen.showOptions(LoadingScreen.java:115)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	at com.google.gapid.MainWindow.updateLoadingScreen(MainWindow.java:101)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	at com.google.gapid.Main$UI.uiStartup(Main.java:161)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	at com.google.gapid.Main$UI.lambda$scheduleIfStillOpen$5(Main.java:183)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	at com.google.gapid.widgets.Widgets.ifNotDisposed(Widgets.java:125)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	at com.google.gapid.widgets.Widgets.lambda$scheduleIfNotDisposed$1(Widgets.java:153)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	at com.google.gapid.widgets.Widgets.lambda$schedule$0(Widgets.java:145)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
> W20191102-185941111[main][Main$UI.lambda$registerWindowExceptionHandler$0] 	... 6 more
> I20191102-185942814[Thread-2][util.Crash2ExceptionHandler$1.run] Crash Report Uploaded Successfully; Crash Report ID: ecd5780e06e02b50
>

**Comment by hevrard** [comment] 2019-11-04 09:55
@stellama0208 @pmuetschard this bug appears on version 2019-10-21, I think you had fixes related to NPE since?

@zwcloud last week we moved the dev-release to an other repo, you can get the latest dev-release from here: https://github.com/google/gapid-dev-releases/releases/latest

**Comment by pmuetschard** [comment] 2019-11-04 16:14
This is a dupe of #3295 and fixed in #3304

**Closed by pmuetschard** 2019-11-04 16:14 UTC
