### ISSUE TITLE
We need --gapir-port for gapis

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#244] opened 2017-04-10 21:25 UTC
I thought we used to have it?

I suspect that gapir is crashing for me, but without logs, or a way to start it stand-alone, or a way to run it under debugger, it is difficult to tell.

**Comment by ben-clayton** [comment] 2017-04-10 22:22
It was intentionally removed as GAPIS needs to pick the right device based on the capture.
Seems like this is a duplicate of https://github.com/google/gapid/issues/233.

**Closed by ben-clayton** 2017-04-10 22:22 UTC
