### ISSUE TITLE
Replay not working on Android devices

### ISSUE THREAD

**Issue by rawnsley** [google/gapid#2668] opened 2019-03-13 09:42 UTC
GAPID Version: 1.5.0:b33134fa99c398ce81dffd642aa11ea53c660518
OS: mac os x x86_64

After successfully capturing a trace from an Android device, GAPID can't replay the output using the same device. If I switch Replay Device to my Mac it can generate the thumbnails OK. This fails on my Pixel 1 with Android 9.0 and on a generic RK3288 Android 5.1 device.

I'm trying to narrow down what I think is a Mali GPU bug so interrogating state on the actual target platform would be very useful.

After about 10 seconds the error dialog comes up with "The gapis server has exited with an error code of: 2" and the details window contains the following:

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x44ec5a6]

goroutine 83 [running]:
github.com/google/gapid/core/app/crash.Crash(0x8381100, 0xdeb6a80)
	core/app/crash/crash.go:89 +0xa7
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x52
panic(0x8381100, 0xdeb6a80)
	GOROOT/src/runtime/panic.go:513 +0x1b9
github.com/google/gapid/gapir/client.(*Connection).Shutdown(0x0, 0x93e93e0, 0xc0006834d0, 0x0, 0x0)
	gapir/client/connection.go:117 +0x26
github.com/google/gapid/gapir/client.(*session).close(0xc000ccea50, 0x93e93e0, 0xc0006834d0)
	gapir/client/session.go:377 +0x47
github.com/google/gapid/gapir/client.(*session).init(0xc000ccea50, 0x93e93e0, 0xc0006834d0, 0x9430840, 0xc0000e67a0, 0xc000138180, 0x0, 0x0, 0x0, 0x0, ...)
	gapir/client/session.go:80 +0x23b
github.com/google/gapid/gapir/client.(*Client).Connect(0xc00012d430, 0x93e93e0, 0xc0006834d0, 0x9430840, 0xc0000e67a0, 0xc000138180, 0x0, 0x0, 0x0)
	gapir/client/client.go:66 +0x276
github.com/google/gapid/gapis/replay.(*manager).connect(0xc000141de0, 0x93e93e0, 0xc000683410, 0x9430840, 0xc0000e67a0, 0xc000138180, 0x0, 0x0, 0x0)
	gapis/replay/replay_connection.go:205 +0x216
github.com/google/gapid/gapis/replay.(*manager).execute(0xc000141de0, 0x93e93e0, 0xc000683410, 0x9430840, 0xc0000e67a0, 0x2cb7c5619ec6d0fe, 0x33aa62cbf94bc338, 0xbe733bf972758983, 0xecac9bcfe55c9361, 0x2787b592ba8aaaaa, ...)
	gapis/replay/batch.go:270 +0x85a
github.com/google/gapid/gapis/replay.(*manager).batch.func1(0x9430840, 0xc0000e67a0, 0xc000472460, 0xe55c9361be733bf9, 0xba8aaaaaecac9bcf, 0x9ec6d0fe2787b592, 0xf94bc3382cb7c561, 0x7275898333aa62cb, 0x837e7c0, 0xdf2a3f8, ...)
	gapis/replay/batch.go:86 +0x41e
github.com/google/gapid/gapis/replay.(*manager).batch(0xc000141de0, 0x93e93e0, 0xc000682e70, 0xc000fd0fc0, 0x1, 0x1, 0x88b0c20, 0x92ef018, 0x88dde80, 0xc0003edb30, ...)
	gapis/replay/batch.go:87 +0x440
github.com/google/gapid/gapis/replay.(*manager).batch-fm(0x93e93e0, 0xc000208540, 0xc000fd0fc0, 0x1, 0x1, 0x88b0c20, 0x92ef018, 0x88dde80, 0xc0003edb30, 0x0)
	gapis/replay/manager.go:146 +0x8d
github.com/google/gapid/gapis/replay/scheduler.(*bin).exec(0xc000e10980, 0x93e93e0, 0xc000208540, 0xc0000e6400)
	gapis/replay/scheduler/scheduler.go:247 +0x271
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run(0xc0001e2ac0, 0x93e93e0, 0xc000208540)
	gapis/replay/scheduler/scheduler.go:180 +0x439
github.com/google/gapid/gapis/replay/scheduler.New.func1()
	gapis/replay/scheduler/scheduler.go:74 +0x3c
github.com/google/gapid/core/app/crash.Go.func1(0xc0001e2ae0)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

**Comment by AWoloszyn** [comment] 2019-03-13 13:38
Is there anything of interest if you run `adb logcat` ?

**Comment by AWoloszyn** [comment] 2019-03-13 13:42
This also looks like a duplicate of 
https://github.com/google/gapid/issues/2620

**Closed by AWoloszyn** 2019-03-13 13:42 UTC

**Comment by rawnsley** [comment] 2019-03-13 13:48
I'll add logcat output to the other issue. I swear I searched, but didn't find anything similar!
