### ISSUE TITLE
Native crash in geometry view

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#1124] opened 2017-09-20 14:03 UTC
```
siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000000

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.lwjgl.opengl.GL11.nglDrawArrays(III)V+0
j  org.lwjgl.opengl.GL11.glDrawArrays(III)V+3
j  com.google.gapid.glviewer.gl.Renderer.draw(Lcom/google/gapid/glviewer/gl/Shader;II)V+7
j  com.google.gapid.glviewer.Geometry$1.render(Lcom/google/gapid/glviewer/gl/Renderer;Lcom/google/gapid/glviewer/Renderable$State;)V+120
j  com.google.gapid.glviewer.GeometryScene.render(Lcom/google/gapid/glviewer/gl/Renderer;)V+103
j  com.google.gapid.widgets.ScenePanel.update(Z)V+73
j  com.google.gapid.widgets.ScenePanel.setSceneData(Ljava/lang/Object;)V+10
j  com.google.gapid.views.GeometryView.setSceneData(Lcom/google/gapid/glviewer/GeometryScene$Data;)V+24
j  com.google.gapid.views.GeometryView.setModel(Lcom/google/gapid/glviewer/geo/Model;)V+220
j  com.google.gapid.views.GeometryView.update(Ljava/util/List;)V+150
j  com.google.gapid.views.GeometryView$1.onUiThreadSuccess(Ljava/util/List;)V+5
j  com.google.gapid.views.GeometryView$1.onUiThreadSuccess(Ljava/lang/Object;)V+5
j  com.google.gapid.rpc.UiErrorCallback.onUiThread(Lcom/google/gapid/rpc/UiErrorCallback$ResultOrError;)V+12
j  com.google.gapid.rpc.UiErrorCallback.onUiThread(Ljava/lang/Object;)V+5
j  com.google.gapid.rpc.UiCallback.lambda$onFinish$0(Ljava/lang/Object;)V+2
j  com.google.gapid.rpc.UiCallback$$Lambda$259.run()V+8
j  com.google.gapid.widgets.Widgets.ifNotDisposed(Lorg/eclipse/swt/widgets/Widget;Ljava/lang/Runnable;)V+8
j  com.google.gapid.widgets.Widgets.lambda$scheduleIfNotDisposed$1(Lorg/eclipse/swt/widgets/Widget;Ljava/lang/Runnable;)V+2
j  com.google.gapid.widgets.Widgets$$Lambda$243.run()V+8
j  com.google.gapid.widgets.Widgets.lambda$schedule$0(J)V+80
j  com.google.gapid.widgets.Widgets$$Lambda$244.run()V+4
j  org.eclipse.swt.widgets.RunnableLock.run()V+11
j  org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Z)Z+37
j  org.eclipse.swt.widgets.Display.runAsyncMessages(Z)Z+5
j  org.eclipse.swt.widgets.Display.readAndDispatch()Z+61
j  org.eclipse.jface.window.Window.runEventLoop(Lorg/eclipse/swt/widgets/Shell;)V+23
j  org.eclipse.jface.window.Window.open()I+49
j  com.google.gapid.Main$UI.show()V+4
j  com.google.gapid.Main.main([Ljava/lang/String;)V+81
v  ~StubRoutines::call_stub
```

**Comment by pmuetschard** [comment] 2017-09-26 19:56
Can you provide me with a reproduction case, or does it seem to happen randomly? Also, do you have the native frames as well? `nglDrawArrays` is a native function that calls `glDrawArrays`, and from the trace it looks like a null pointer problem. This could mean that the finding `glDrawArrays` in `nglDrawArrays` is broken (unlikely, since it would always fail), or the issue is in the GL driver.

**Comment by ben-clayton** [comment] 2017-10-18 11:01
There's not enough to go on here. Closing. Please reopen if there's more information.

**Closed by ben-clayton** 2017-10-18 11:01 UTC
Labels: bug, GAPIC, linux, triaged
