### ISSUE TITLE
Shader Programs should link to individual Shaders

### ISSUE THREAD

**Issue by tomgoogle** [google/gapid#1216] opened 2017-10-18 00:36 UTC
For GLES, jumping to the currently bound Vertex/Fragment shaders is long winded - you have to generally jump through the State window to find the appropriate Vertex/Fragment shaders for the currently bound Program.

It would be really nice to have at a minimum the shader ID shown next to the Vertex/Fragment shaders in the Programs view, and at a push a link that takes you straight to the right shader in the Shaders tab.

<img width="791" alt="screen shot 2017-10-17 at 5 29 46 pm" src="https://user-images.githubusercontent.com/25167811/31695836-be763a4c-b361-11e7-9311-886c3c64fbda.png">

**Comment by dsrbecky** [comment] 2017-10-18 10:19
I find this view a bit odd in general.
We have two tabs which serve the same purpose (show shaders) but slightly differently.
The "all shaders on the screen" approach will not scale if add support for the other shader types.

My suggestion would to remove the Shader tab alogether, show only one shader source in the program at the time (selectable by tab or toolbar), and making it possible to edit the shaders here as well.

**Comment by AWoloszyn** [comment] 2017-11-05 15:58
I think a pipeline view would solve this problem as well. For a longer-term solution. (What was the entire state of the drawing pipeline for the last draw call, shaders, blend state, buffers, etc etc etc).

**Comment by AWoloszyn** [comment] 2018-10-30 17:46
This is effectively a dupe of #387, closing

**Closed by AWoloszyn** 2018-10-30 17:46 UTC
