### ISSUE TITLE
Not detecting my device

### ISSUE THREAD

**Issue by clarng** [google/gapid#1570] opened 2018-01-24 04:07 UTC
I am on MacOS and the tool is not able to discover my device that is connected through usb. The Device dropdown is empty, although I see my phone via adb devices. The path to adb I gave is /opt/android_sdk/platform_tools/. Are there ways I can further debug this on my end? I tried this on 0.9.0 and 1.0.1 release.

Thanks

**Comment by ben-clayton** [comment] 2018-01-24 10:06
Hi @clarng,

A few things to try:
* Have you confirmed that the command line adb is the same as the one you've used in your GAPID path? You can check with `which adb`.
* What is the output of `adb devices`?
* If you can find the GAPID executables directory - do you see anything aside from the host in the output of`gapit devices`?

**Comment by clarng** [comment] 2018-01-24 18:34
I can see the device from gapid devices

18:31:59.639 I: <gapit> Exec: /Applications/GAPID.app/Contents/MacOS/gapis --idle-timeout 1m --log-level Info --log-style brief --gapis-auth-token ON2XEM0G
18:31:59.700 I: <gapis> 18:31:59.700 I: <gapis> Adding new device
18:31:59.700 I: <gapis> 18:31:59.700 I: <gapis> New scheduler for device: 6e54a9de76f0b8941a44a9bcb131863e4de84804
18:31:59.704 I: <gapis> Bound on port '59110'
18:31:59.704 I: <gapis> 18:31:59.704 I: <gapis> Starting grpc server
10:32:00.253 I: [gapidapk.EnsureInstalled] <gapis> Examining gapid.apk on host...
10:32:00.258 I: [gapidapk.EnsureInstalled] <gapis> Looking for gapid.apk...
10:32:00.792 I: [gapidapk.EnsureInstalled] <gapis> Found gapid package...
10:32:01.261 I: <gapis> Adding new device
-- Device 0: 6e54a9de76f0b8941a44a9bcb131863e4de84804 --
10:32:01.261 I: <gapis> Adding new device
10:32:01.261 I: <gapis> New scheduler for device: b2d4cbddc4c52d162aa83977f417b2b8d3efa231
{
  "id": {
    "data": "blSp3nbwuJQaRKm8sTGGPk3oSAQ="
  },
  "Name": "clng-mbp",
  "Configuration": {
    "OS": {
      "Kind": 2,
      "Name": "OSX",
      "Major": 10,
      "Minor": 13,
      "Point": 1
    },
    "Hardware": {
      "Name": "MacBookPro14,3",
      "CPU": {
        "Name": "Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz",
        "Vendor": "GenuineIntel",
        "Architecture": 4,
        "Cores": 8
      },
      "GPU": {}
    },
    "ABIs": [
      {
        "Name": "X86_64",
        "OS": 2,
        "Architecture": 4,
        "MemoryLayout": {
          "Endian": 2,
          "Pointer": {
            "size": 8,
            "alignment": 8
          },
          "Integer": {
            "size": 4,
            "alignment": 4
          },
          "Size": {
            "size": 8,
            "alignment": 8
          },
          "Char": {
            "size": 1,
            "alignment": 1
          },
          "I64": {
            "size": 8,
            "alignment": 8
          },
          "I32": {
            "size": 4,
            "alignment": 4
          },
          "I16": {
            "size": 2,
            "alignment": 2
          },
          "I8": {
            "size": 1,
            "alignment": 1
          },
          "F64": {
            "size": 8,
            "alignment": 8
          },
          "F32": {
            "size": 4,
            "alignment": 4
          },
          "F16": {
            "size": 2,
            "alignment": 2
          }
        }
      }
    ],
    "Drivers": {
      "OpenGL": {
        "Extensions": [
          "GL_ARB_blend_func_extended",
          "GL_ARB_draw_buffers_blend",
          "GL_ARB_draw_indirect",
          "GL_ARB_ES2_compatibility",
          "GL_ARB_explicit_attrib_location",
          "GL_ARB_gpu_shader_fp64",
          "GL_ARB_gpu_shader5",
          "GL_ARB_instanced_arrays",
          "GL_ARB_internalformat_query",
          "GL_ARB_occlusion_query2",
          "GL_ARB_sample_shading",
          "GL_ARB_sampler_objects",
          "GL_ARB_separate_shader_objects",
          "GL_ARB_shader_bit_encoding",
          "GL_ARB_shader_subroutine",
          "GL_ARB_shading_language_include",
          "GL_ARB_tessellation_shader",
          "GL_ARB_texture_buffer_object_rgb32",
          "GL_ARB_texture_cube_map_array",
          "GL_ARB_texture_gather",
          "GL_ARB_texture_query_lod",
          "GL_ARB_texture_rgb10_a2ui",
          "GL_ARB_texture_storage",
          "GL_ARB_texture_swizzle",
          "GL_ARB_timer_query",
          "GL_ARB_transform_feedback2",
          "GL_ARB_transform_feedback3",
          "GL_ARB_vertex_attrib_64bit",
          "GL_ARB_vertex_type_2_10_10_10_rev",
          "GL_ARB_viewport_array",
          "GL_EXT_debug_label",
          "GL_EXT_debug_marker",
          "GL_EXT_depth_bounds_test",
          "GL_EXT_texture_compression_s3tc",
          "GL_EXT_texture_filter_anisotropic",
          "GL_EXT_texture_mirror_clamp",
          "GL_EXT_texture_sRGB_decode",
          "GL_APPLE_client_storage",
          "GL_APPLE_container_object_shareable",
          "GL_APPLE_flush_render",
          "GL_APPLE_object_purgeable",
          "GL_APPLE_rgb_422",
          "GL_APPLE_row_bytes",
          "GL_APPLE_texture_range",
          "GL_ATI_texture_mirror_once",
          "GL_NV_texture_barrier"
        ],
        "Renderer": "AMD Radeon Pro 555 OpenGL Engine",
        "Vendor": "ATI Technologies Inc.",
        "Version": "4.1 ATI-1.58.32",
        "UniformBufferAlignment": 256,
        "MaxTransformFeedbackSeparateAttribs": 4,
        "MaxTransformFeedbackInterleavedComponents": 64
      },
      "Vulkan": {}
    }
  }
}
-- Device 1: b2d4cbddc4c52d162aa83977f417b2b8d3efa231 --
{
  "id": {
    "data": "stTL3cTFLRYqqDl39BeyuNPvojE="
  },
  "Serial": "712KPRW1015390",
  "Name": "712KPRW1015390",
  "Configuration": {
    "OS": {
      "Kind": 4,
      "Name": "8.1.0",
      "Build": "OPM1.171019.013",
      "Major": 8,
      "Minor": 1
    },
    "Hardware": {
      "Name": "taimen",
      "CPU": {
        "Architecture": 2
      },
      "GPU": {}
    },
    "ABIs": [
      {
        "Name": "arm64-v8a",
        "OS": 4,
        "Architecture": 2,
        "MemoryLayout": {
          "Endian": 2,
          "Pointer": {
            "size": 8,
            "alignment": 8
          },
          "Integer": {
            "size": 8,
            "alignment": 8
          },
          "Size": {
            "size": 8,
            "alignment": 8
          },
          "Char": {
            "size": 1,
            "alignment": 1
          },
          "I64": {
            "size": 8,
            "alignment": 8
          },
          "I32": {
            "size": 4,
            "alignment": 4
          },
          "I16": {
            "size": 2,
            "alignment": 2
          },
          "I8": {
            "size": 1,
            "alignment": 1
          },
          "F64": {
            "size": 8,
            "alignment": 8
          },
          "F32": {
            "size": 4,
            "alignment": 4
          },
          "F16": {
            "size": 2,
            "alignment": 2
          }
        }
      },
      {
        "Name": "armeabi-v7a",
        "OS": 4,
        "Architecture": 1,
        "MemoryLayout": {
          "Endian": 2,
          "Pointer": {
            "size": 4,
            "alignment": 4
          },
          "Integer": {
            "size": 4,
            "alignment": 4
          },
          "Size": {
            "size": 4,
            "alignment": 4
          },
          "Char": {
            "size": 1,
            "alignment": 1
          },
          "I64": {
            "size": 8,
            "alignment": 8
          },
          "I32": {
            "size": 4,
            "alignment": 4
          },
          "I16": {
            "size": 2,
            "alignment": 2
          },
          "I8": {
            "size": 1,
            "alignment": 1
          },
          "F64": {
            "size": 8,
            "alignment": 8
          },
          "F32": {
            "size": 4,
            "alignment": 4
          },
          "F16": {
            "size": 2,
            "alignment": 2
          }
        }
      },
      {
        "Name": "armeabi",
        "OS": 4,
        "Architecture": 1,
        "MemoryLayout": {
          "Endian": 2,
          "Pointer": {
            "size": 4,
            "alignment": 4
          },
          "Integer": {
            "size": 4,
            "alignment": 4
          },
          "Size": {
            "size": 4,
            "alignment": 4
          },
          "Char": {
            "size": 1,
            "alignment": 1
          },
          "I64": {
            "size": 8,
            "alignment": 8
          },
          "I32": {
            "size": 4,
            "alignment": 4
          },
          "I16": {
            "size": 2,
            "alignment": 2
          },
          "I8": {
            "size": 1,
            "alignment": 1
          },
          "F64": {
            "size": 8,
            "alignment": 8
          },
          "F32": {
            "size": 4,
            "alignment": 4
          },
          "F16": {
            "size": 2,
            "alignment": 2
          }
        }
      },
      {
        "Name": "arm64-v8a",
        "OS": 4,
        "Architecture": 2,
        "MemoryLayout": {
          "Endian": 2,
          "Pointer": {
            "size": 8,
            "alignment": 8
          },
          "Integer": {
            "size": 8,
            "alignment": 8
          },
          "Size": {
            "size": 8,
            "alignment": 8
          },
          "Char": {
            "size": 1,
            "alignment": 1
          },
          "I64": {
            "size": 8,
            "alignment": 8
          },
          "I32": {
            "size": 4,
            "alignment": 4
          },
          "I16": {
            "size": 2,
            "alignment": 2
          },
          "I8": {
            "size": 1,
            "alignment": 1
          },
          "F64": {
            "size": 8,
            "alignment": 8
          },
          "F32": {
            "size": 4,
            "alignment": 4
          },
          "F16": {
            "size": 2,
            "alignment": 2
          }
        }
      },
      {
        "Name": "armeabi-v7a",
        "OS": 4,
        "Architecture": 1,
        "MemoryLayout": {
          "Endian": 2,
          "Pointer": {
            "size": 4,
            "alignment": 4
          },
          "Integer": {
            "size": 4,
            "alignment": 4
          },
          "Size": {
            "size": 4,
            "alignment": 4
          },
          "Char": {
            "size": 1,
            "alignment": 1
          },
          "I64": {
            "size": 8,
            "alignment": 8
          },
          "I32": {
            "size": 4,
            "alignment": 4
          },
          "I16": {
            "size": 2,
            "alignment": 2
          },
          "I8": {
            "size": 1,
            "alignment": 1
          },
          "F64": {
            "size": 8,
            "alignment": 8
          },
          "F32": {
            "size": 4,
            "alignment": 4
          },
          "F16": {
            "size": 2,
            "alignment": 2
          }
        }
      },
      {
        "Name": "armeabi",
        "OS": 4,
        "Architecture": 1,
        "MemoryLayout": {
          "Endian": 2,
          "Pointer": {
            "size": 4,
            "alignment": 4
          },
          "Integer": {
            "size": 4,
            "alignment": 4
          },
          "Size": {
            "size": 4,
            "alignment": 4
          },
          "Char": {
            "size": 1,
            "alignment": 1
          },
          "I64": {
            "size": 8,
            "alignment": 8
          },
          "I32": {
            "size": 4,
            "alignment": 4
          },
          "I16": {
            "size": 2,
            "alignment": 2
          },
          "I8": {
            "size": 1,
            "alignment": 1
          },
          "F64": {
            "size": 8,
            "alignment": 8
          },
          "F32": {
            "size": 4,
            "alignment": 4
          },
          "F16": {
            "size": 2,
            "alignment": 2
          }
        }
      }
    ],
    "Drivers": {
      "OpenGL": {
        "Extensions": [
          "GL_OES_EGL_image",
          "GL_OES_EGL_image_external",
          "GL_OES_EGL_sync",
          "GL_OES_vertex_half_float",
          "GL_OES_framebuffer_object",
          "GL_OES_rgb8_rgba8",
          "GL_OES_compressed_ETC1_RGB8_texture",
          "GL_AMD_compressed_ATC_texture",
          "GL_KHR_texture_compression_astc_ldr",
          "GL_KHR_texture_compression_astc_hdr",
          "GL_OES_texture_compression_astc",
          "GL_OES_texture_npot",
          "GL_EXT_texture_filter_anisotropic",
          "GL_EXT_texture_format_BGRA8888",
          "GL_OES_texture_3D",
          "GL_EXT_color_buffer_float",
          "GL_EXT_color_buffer_half_float",
          "GL_QCOM_alpha_test",
          "GL_OES_depth24",
          "GL_OES_packed_depth_stencil",
          "GL_OES_depth_texture",
          "GL_OES_depth_texture_cube_map",
          "GL_EXT_sRGB",
          "GL_OES_texture_float",
          "GL_OES_texture_float_linear",
          "GL_OES_texture_half_float",
          "GL_OES_texture_half_float_linear",
          "GL_EXT_texture_type_2_10_10_10_REV",
          "GL_EXT_texture_sRGB_decode",
          "GL_OES_element_index_uint",
          "GL_EXT_copy_image",
          "GL_EXT_geometry_shader",
          "GL_EXT_tessellation_shader",
          "GL_OES_texture_stencil8",
          "GL_EXT_shader_io_blocks",
          "GL_OES_shader_image_atomic",
          "GL_OES_sample_variables",
          "GL_EXT_texture_border_clamp",
          "GL_EXT_multisampled_render_to_texture",
          "GL_EXT_multisampled_render_to_texture2",
          "GL_OES_shader_multisample_interpolation",
          "GL_EXT_texture_cube_map_array",
          "GL_EXT_draw_buffers_indexed",
          "GL_EXT_gpu_shader5",
          "GL_EXT_robustness",
          "GL_EXT_texture_buffer",
          "GL_EXT_shader_framebuffer_fetch",
          "GL_ARM_shader_framebuffer_fetch_depth_stencil",
          "GL_OES_texture_storage_multisample_2d_array",
          "GL_OES_sample_shading",
          "GL_OES_get_program_binary",
          "GL_EXT_debug_label",
          "GL_KHR_blend_equation_advanced",
          "GL_KHR_blend_equation_advanced_coherent",
          "GL_QCOM_tiled_rendering",
          "GL_ANDROID_extension_pack_es31a",
          "GL_EXT_primitive_bounding_box",
          "GL_OES_standard_derivatives",
          "GL_OES_vertex_array_object",
          "GL_EXT_disjoint_timer_query",
          "GL_KHR_debug",
          "GL_EXT_YUV_target",
          "GL_EXT_sRGB_write_control",
          "GL_EXT_texture_norm16",
          "GL_EXT_discard_framebuffer",
          "GL_OES_surfaceless_context",
          "GL_OVR_multiview",
          "GL_OVR_multiview2",
          "GL_EXT_texture_sRGB_R8",
          "GL_KHR_no_error",
          "GL_EXT_debug_marker",
          "GL_OES_EGL_image_external_essl3",
          "GL_OVR_multiview_multisampled_render_to_texture",
          "GL_EXT_buffer_storage",
          "GL_EXT_external_buffer",
          "GL_EXT_blit_framebuffer_params",
          "GL_EXT_clip_cull_distance",
          "GL_EXT_protected_textures",
          "GL_EXT_shader_non_constant_global_initializers",
          "GL_QCOM_framebuffer_foveated",
          "GL_QCOM_shader_framebuffer_fetch_noncoherent",
          "GL_EXT_EGL_image_array",
          "GL_NV_shader_noperspective_interpolation"
        ],
        "Renderer": "Adreno (TM) 540",
        "Vendor": "Qualcomm",
        "Version": "OpenGL ES 3.2 V@258.0 (GIT@594927b, I916dfac403) (Date:10/11/17)",
        "UniformBufferAlignment": 32,
        "MaxTransformFeedbackSeparateAttribs": 4,
        "MaxTransformFeedbackInterleavedComponents": 128
      },
      "Vulkan": {}
    }
  }
}

**Comment by ben-clayton** [comment] 2018-03-13 18:57
I strongly suspect this is a dupe of #1326.
There's UI issues around updating the dialog that are catching out a lot of people.

**Closed by ben-clayton** 2018-03-13 18:57 UTC

**Comment by CarlLee** [comment] 2019-01-23 03:36
Same problem. I can find device using gapid devices but can't find it in dialog even after multiple reboot of phone/pc/gapid.

**Comment by AWoloszyn** [comment] 2019-01-23 14:26
The path in the UI should be the path to the adb executable. (Not the directory containing adb).
If that still does not fix, please let me know.
