### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by wenjiangye** [google/gapid#3531] opened 2019-12-11 16:58 UTC
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: 
--- *initialcmds.InitialCmdsResolvable ---
 capture:<ID:<data:"\222\001Is\032\203\334\266\017\210z~\0275\311\031\264\242\023\n" > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/initialcmds/initial_commands.go:40  github.com/google/gapid/gapis/resolve/initialcmds.InitialCommands
  gapis/resolve/resources.go:58  github.com/google/gapid/gapis/resolve.(*ResourcesResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/initialcmds/initial_commands.go:40  github.com/google/gapid/gapis/resolve/initialcmds.InitialCommands
  gapis/resolve/resources.go:58  github.com/google/gapid/gapis/resolve.(*ResourcesResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

--- *resolve.ResourcesResolvable ---
 capture:<ID:<data:"\222\001Is\032\203\334\266\017\210z~\0275\311\031\264\242\023\n" > > config:<replay_device:<ID:<data:"\260\252M\312\316|\253\350^\027&\225\250W\337\223\211\024\271#" > > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/resources.go:33  github.com/google/gapid/gapis/resolve.Resources
  gapis/resolve/resolve.go:340  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:270  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/resources.go:33  github.com/google/gapid/gapis/resolve.Resources
  gapis/resolve/resolve.go:340  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:270  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

--- *resolve.GetResolvable ---
 path:<resources:<capture:<ID:<data:"\222\001Is\032\203\334\266\017\210z~\0275\311\031\264\242\023\n" > > > > config:<replay_device:<ID:<data:"\260\252M\312\316|\253\350^\027&\225\250W\337\223\211\024\271#" > > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:389  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8914  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8916  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:389  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8914  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8916  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream
 [recovered]
	panic: 
--- *initialcmds.InitialCmdsResolvable ---
 capture:<ID:<data:"\222\001Is\032\203\334\266\017\210z~\0275\311\031\264\242\023\n" > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/initialcmds/initial_commands.go:40  github.com/google/gapid/gapis/resolve/initialcmds.InitialCommands
  gapis/resolve/resources.go:58  github.com/google/gapid/gapis/resolve.(*ResourcesResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/initialcmds/initial_commands.go:40  github.com/google/gapid/gapis/resolve/initialcmds.InitialCommands
  gapis/resolve/resources.go:58  github.com/google/gapid/gapis/resolve.(*ResourcesResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

--- *resolve.ResourcesResolvable ---
 capture:<ID:<data:"\222\001Is\032\203\334\266\017\210z~\0275\311\031\264\242\023\n" > > config:<replay_device:<ID:<data:"\260\252M\312\316|\253\350^\027&\225\250W\337\223\211\024\271#" > > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/resources.go:33  github.com/google/gapid/gapis/resolve.Resources
  gapis/resolve/resolve.go:340  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:270  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/resources.go:33  github.com/google/gapid/gapis/resolve.Resources
  gapis/resolve/resolve.go:340  github.com/google/gapid/gapis/resolve.ResolveInternal
  gapis/resolve/resolve.go:270  github.com/google/gapid/gapis/resolve.ResolveService
  gapis/resolve/get.go:33  github.com/google/gapid/gapis/resolve.(*GetResolvable).Resolve
  gapis/database/memory.go:137  github.com/google/gapid/gapis/database.(*record).resolve
  gapis/database/memory.go:241  github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1
  core/app/crash/crash.go:65  github.com/google/gapid/core/app/crash.Go.func1

--- *resolve.GetResolvable ---
 path:<resources:<capture:<ID:<data:"\222\001Is\032\203\334\266\017\210z~\0275\311\031\264\242\023\n" > > > > config:<replay_device:<ID:<data:"\260\252M\312\316|\253\350^\027&\225\250W\337\223\211\024\271#" > > > 
 Store():
  gapis/database/database.go:56  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:389  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8914  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8916  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream

 Build() #0:
  gapis/database/database.go:60  github.com/google/gapid/gapis/database.Build
  gapis/resolve/get.go:26  github.com/google/gapid/gapis/resolve.Get
  gapis/server/server.go:389  github.com/google/gapid/gapis/server.(*server).Get
  gapis/server/grpc.go:214  github.com/google/gapid/gapis/server.(*grpcServer).Get
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8914  github.com/google/gapid/gapis/service._Gapid_Get_Handler.func1
  core/app/auth/auth.go:110  github.com/google/gapid/core/app/auth.ServerInterceptor.func1
  bazel-out/x64_windows-opt/bin/gapis/service/windows_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:8916  github.com/google/gapid/gapis/service._Gapid_Get_Handler
  external/org_golang_google_grpc/server.go:971  google.golang.org/grpc.(*Server).processUnaryRPC
  external/org_golang_google_grpc/server.go:1250  google.golang.org/grpc.(*Server).handleStream

[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1d1b15f]

goroutine 461 [running]:
github.com/google/gapid/core/app/crash.Crash(0x54a54e0, 0xc037dc6a50)
	core/app/crash/crash.go:89 +0xae
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x59
panic(0x54a54e0, 0xc037dc6a50)
	GOROOT/src/runtime/panic.go:522 +0x1c3
github.com/google/gapid/gapis/database.(*memory).resolvePanicHandler(0xc000004460, 0x6acca40, 0xc01f9d8330)
	gapis/database/debug.go:106 +0x775
panic(0x564ea00, 0x478d200)
	GOROOT/src/runtime/panic.go:522 +0x1c3
github.com/google/gapid/gapis/api/gles.TextureUnitʳ.ID(...)
	bazel-out/x64_windows-opt/bin/gapis/api/gles/api_amrp.go:23754
github.com/google/gapid/gapis/api/gles.(*stateBuilder).contextObjectPostEGLImage(0xc00012ee00, 0x6acca40, 0xc01f9d8420, 0x72969b5d80, 0xc035518960, 0x104a3)
	gapis/api/gles/state_builder.go:493 +0x103f
github.com/google/gapid/gapis/api/gles.API.RebuildState(0x6acca40, 0xc01f9d8420, 0xc01c76a540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	gapis/api/gles/state_builder.go:102 +0x5bd
github.com/google/gapid/gapis/resolve/initialcmds.(*InitialCmdsResolvable).Resolve(0xc01f9d8240, 0x6acca40, 0xc01f9d8420, 0xc01f9d8420, 0xc000625f00, 0x2, 0x2)
	gapis/resolve/initialcmds/initial_commands.go:62 +0x1e6
github.com/google/gapid/gapis/database.(*record).resolve(0xc034a00420, 0x6acca40, 0xc01f9d8420, 0x0, 0x0)
	gapis/database/memory.go:137 +0x229
github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1()
	gapis/database/memory.go:241 +0x13b
github.com/google/gapid/core/app/crash.Go.func1(0xc01f9d82d0)
	core/app/crash/crash.go:65 +0x4a
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x46

GAPID Version: 1.6.1:338bb67b0fe291f56f31d69f11ea1a45ed7cfeb6
OS: windows 10 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by hevrard** [comment] 2019-12-16 10:43
Thanks for reporting, I can see you are using the stable GAPID version 1.6.1, can you try to reproduce on the preview unstable dev-release version:
https://github.com/google/gapid-dev-releases/releases/latest

Please let us know if you can see the same error with the dev-release version.

**Comment by hevrard** [comment] 2019-12-16 10:44
I can see you already tried the dev-release and filed issue #3532 

Closing this one as a duplicate of #3532

**Closed by hevrard** 2019-12-16 10:44 UTC
Labels: needs more information
