### ISSUE TITLE
The gapis server has exited with an error code of: -42

### ISSUE THREAD

**Issue by theee0703** [google/gapid#3450] opened 2019-11-25 08:34 UTC
GAPID Version: 1.6.1:338bb67b0fe291f56f31d69f11ea1a45ed7cfeb6
OS: windows 10 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

1. open trace which colleagues provides with v1.6.1 recorded.
2. see the error log 

ps. I can open the trace with other PC , but failed on my laptop.

**Comment by pau-baiget** [comment] 2019-12-09 12:16
Thanks @theee0703 for your bug report. Could you please add more details so we can identify the source of the issue? In particular, please provide the contents of the temp folder (gapi*log files) and a full logcat.

Also, please try the latest [dev release](https://github.com/google/gapid-dev-releases
) and check if you can still reproduce the issue. Thanks!!

**Comment by pau-baiget** [comment] 2020-01-09 11:49
Closing this issue since it's been with "needs more information" for a month. @theee0703 please re-open if you see this issue again and are able to provide the information requested in the previous comment. Thank you!|

**Closed by pau-baiget** 2020-01-09 11:49 UTC
Labels: needs more information
