### ISSUE TITLE
How to let GAPID replay gfxtrace file with native function?

### ISSUE THREAD

**Issue by AwinHuang** [google/gapid#2615] opened 2019-02-19 07:52 UTC
For example, I record a gfxtrace file from my android phone, it's in EGL environment.
The API sequence will like below:

```
eglInitialize()
eglChooseConfig()
eglCreateWindowSurface()
eglMakeCurrent()
glClear()
glDrawArrays()
...
eglSwaoBuffers()
```

Is there any way that I can replay this file with the same API call?
I use `gapit video` to replay, but `gapit video` will convert some function into another function, e.g. I use `gapit video xxx.gfxtrace`, the API call will convert to below:

```
glxQueryVersion()
glxChooseFBConfig()
glxCreatePBuffer() <-- CreateWindow became pbuffer!
glxMakeContextCurrent() 
glClear()
glDrawArrays()
...
eglSwaoBuffers() <-- *disappear*
```

**Is there a way to replay gfxtrace file in original function and sequence?**

**Comment by ben-clayton** [comment] 2019-02-19 09:44
> Is there a way to replay gfxtrace file in original function and sequence?

Currently not, no.

GAPID was intended to trace and replay GLES and Vulkan command streams accurately, but has abstracted EGL and the windowing APIs so replays can be performed on Android (using EGL) and on Windows (XGL), macOS (NSOpenGL), and Linux (GLX).

That said: having support for more accurate replays (including EGL) may be becoming more of a priority than cross-device replay, so this may change in the future.

There is also an effort to add a mode to replay using a true window and backbuffer instead of a pbuffer on Android.

What are your requirements here? It may be possible for us to meet your needs without dropping all the EGL abstractions (which would be a more substantial change).

**Comment by AwinHuang** [comment] 2019-02-19 10:11
Hi clayton, thanks for your replay.

I build a internal EGL environment and GL driver on Linux. And which will use on Android in the future. 
So it's important to replay each function of gfxtrace file, so I can review(and debug) the full flow on Linux.

For replay purpose, if I record a file on Android, and "replay" it on Linux, if EGL related functions were ignored, I can not use(and debug) my own EGL code on PC.

I think keep all the EGL functions are useful, how do I do that?
Thanks.

**Comment by ben-clayton** [comment] 2019-02-19 14:04
> For replay purpose, if I record a file on Android, and "replay" it on Linux, if EGL related functions were ignored, I can not use(and debug) my own EGL code on PC.

Correct. It is not typical for desktop Linux to have an EGL library, so for replay on Linux all EGL calls are transformed into GLX.

> I think keep all the EGL functions are useful, how do I do that?

Let me sync with the team and get back to you.

**Comment by AwinHuang** [comment] 2019-02-25 02:03
I found the GLSL were also changed.
The original code:
```
#version 100
attribute vec4 position;
attribute float vtxAlpha;
uniform mat4 projection;
uniform mat4 transform;
varying float alpha;

void main(void) {
    alpha = vtxAlpha;
    vec4 transformedPosition = projection * transform * position;
    gl_Position = transformedPosition;
}
```
The GAPID GLSL
```
#version 330

#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

uniform mat4 u_MVPMatrix;

out vec4 v_Color;
in vec4 a_Color;
in vec4 a_Position;

void main()
{
    v_Color = a_Color;
    gl_Position = u_MVPMatrix * a_Position;
}
```
Why does GAPID need to change GLSL?
Would you please tell where is the code that GAPID transform the GLSL from `version 100` to `version 330`?

Thanks

**Comment by AwinHuang** [comment] 2019-02-25 09:22
I found it.
In `gapis/api/gles/compat.go`, `case *GlCompileShader`
```
res, err := shadertools.ConvertGlsl(src, &opts)
```
above code transform GLSL to version 330.

**Comment by pmuetschard** [comment] 2019-02-28 23:15
When replaying on destop we translate the GLES calls into OpenGL (desktop), since the replay will create an OpenGL context, not a GLES one. Shaders need to be fixed to compile on OpenGL's GLSL, not GLES GLSL.

Having desktop GLES replay sounds interesting, but is far off of our roadmap. So, I'm afraid I have to close this issue as "Wont Fix" for now. If you are interested in trying to get this to work in a hacky way for yourself, you would need to
1) Make it look like your desktop is ES to gapis (hack `ParseVersion` in `gapis/api/gles/version.go`) to disable GLES->GL translation
2) Change `gapir/cc/linux/gles_renderer.cpp` to use libGLESv2 instead of libGL. You can use the Android one for a basis.

**Closed by pmuetschard** 2019-02-28 23:15 UTC

**Comment by pemgithub** [comment] 2019-06-24 18:07
If I record (capture) GLES Android then replay on Android...  How accurate is the replay?  Are the GLES calls (and GLSL) 100% accurate?  Does anything change besides (window becomes pbuffer)?

This is for GPU testing (hardware, drivers, firmware).  Though I suspect replay accuracy is also important for game/app development.

@ben-clayton  @pmuetschard  @AwinHuang

**Comment by AWoloszyn** [comment] 2019-06-24 18:48
I will let @ben-clayton  and @pmuetschard elaborate, since they have a better understanding, but the code that does this is located here
https://github.com/google/gapid/blob/ab5dcbcd793f38818236618519b83f765e0d19a9/gapis/api/gles/compat.go

As far as I am aware, if you are replaying on the same device, the only changes that I am aware of are:
`Replaying into pbuffers`
`A few changes to how contexts are created/shared`
`Some changes if you are using external textures`
`Some modifications if you are using multiview`

Other than that I do not think there are any meaningful changes. Specifically, if your replay device is Android, shaders are left unmodified.
```go
		case *GlShaderSource:
			if version.IsES { // No compat required.
				out.MutateAndWrite(ctx, id, cmd)
				return
			}
```
```go
		case *GlCompileShader:
			if version.IsES { // No compat required.
				out.MutateAndWrite(ctx, id, cmd)
				return
			}
```
