### ISSUE TITLE
Tracing on Android x86_64 does not work.

### ISSUE THREAD

**Issue by tpalli** [google/gapid#2107] opened 2018-07-31 08:21 UTC
I'm not sure what is going wrong here but I'm trying to use gapid to capture trace from Vulkan application and it does not seem to work for me.

Gapid version: Version 1.1.0:874eed8e0372b54db789835e1ad36cb641e9fbea

Here is the log from gapid:
```
Press enter to stop capturing...
08:15:35.413 I: [Try ABI: x86_64⇒gapidapk.EnsureInstalled] <gapit> Examining gapid.apk on host...
08:15:35.413 I: [Try ABI: x86_64⇒gapidapk.EnsureInstalled] <gapit> Opening gapid.apk
   Cause: read /opt/gapid: is a directory
08:15:35.413 I: [Try ABI: x86_64⇒gapidapk.EnsureInstalled] <gapit> Examining gapid.apk on host...
08:15:35.413 I: [Try ABI: x86_64⇒gapidapk.EnsureInstalled] <gapit> Opening gapid.apk
   Cause: read /opt/gapid: is a directory
08:15:35.413 I: [Try ABI: x86⇒gapidapk.EnsureInstalled] <gapit> Examining gapid.apk on host...
08:15:35.419 I: [Try ABI: x86⇒gapidapk.EnsureInstalled] <gapit> Looking for gapid.apk...
08:15:35.726 I: [Try ABI: x86⇒gapidapk.EnsureInstalled] <gapit> Found gapid package...
08:15:35.726 I: [startDevInfoService] <gapit> Attempt to start service: com.google.android.gapid.DeviceInfoService
08:15:36.029 I: <gapit> Adding new device
08:15:36.029 I: <gapit> Device list:
08:15:36.029 I: <gapit>   192.168.43.140:5555
08:15:36.592 I: <gapit> Package is debuggable
08:15:36.816 I: [start] <gapit> Turning device screen on
08:15:36.940 I: [start] <gapit> Checking for lockscreen
08:15:37.059 W: [start] <gapit> Couldn't determine lockscreen state: 
   Cause: Couldn't get lockscreen state
08:15:37.059 I: [start] <gapit> Checking gapid.apk is installed
08:15:37.059 I: [Try ABI: x86_64⇒gapidapk.EnsureInstalled⇒start] <gapit> Examining gapid.apk on host...
08:15:37.059 I: [Try ABI: x86_64⇒gapidapk.EnsureInstalled⇒start] <gapit> Opening gapid.apk
   Cause: read /opt/gapid: is a directory
08:15:37.059 I: [Try ABI: x86_64⇒gapidapk.EnsureInstalled⇒start] <gapit> Examining gapid.apk on host...
08:15:37.059 I: [Try ABI: x86_64⇒gapidapk.EnsureInstalled⇒start] <gapit> Opening gapid.apk
   Cause: read /opt/gapid: is a directory
08:15:37.059 I: [start] <gapit> Forwarding
08:15:37.175 I: [start] <gapit> Starting activity in debug mode
08:15:37.644 I: [start] <gapit> Forwarding TCP port 43873 -> JDWP pid 5401
08:15:37.648 I: [start] <gapit> Connecting to JDWP
08:15:37.902 I: [start] <gapit> Waiting for ApplicationLoaders.getClassLoader()
08:15:47.066 I: [start] <gapit> Waiting for Application Creation
08:15:47.177 I: [start] <gapit>    Waiting for Application.<init>()
08:16:02.908 I: [start] <gapit>    Waiting for android.app.Application.onCreate()
08:16:03.312 I: [start] <gapit> Installing interceptor libraries
08:16:28.427 I: [start] <gapit> GVR library not found
08:16:32.187 I: [start] <gapit> Waiting for connection to localhost:39345...
08:16:43.943 W: [start] <gapit> Failed to read packet. Error: read tcp 127.0.0.1:43672->127.0.0.1:43873: use of closed network connection
08:16:43.947 E: <gapit> Main failed
Error: loadGAPII
   Cause: Exception raised calling: public static void java.lang.System.load(java.lang.String)
java.lang.UnsatisfiedLinkError: 
```

**Comment by tpalli** [comment] 2018-07-31 08:25
Some more information, host is Ubuntu 16.04 and target is Android machine (x86_64).

**Comment by tpalli** [comment] 2018-08-02 05:53
Android version used is 8.1.0, this is on Android Celadon (https://01.org/projectceladon/about). Would be great to a working capture/playback functionality between desktop and Android device. We used to have this with apitrace but that does not work on Android anymore.

**Comment by AWoloszyn** [comment] 2018-08-02 13:31
Is the .apk in question an x86 or an x86_64 apk?

**Comment by tpalli** [comment] 2018-08-13 10:57
This was x86_64 and now that you mentioned it I can see that the prebuilt libraries in gapid package are only for x86. Is this the issue?

**Comment by AWoloszyn** [comment] 2018-08-14 15:15
That is most likely the issue. We do not ship x86_64 binaries for android. The main reason for this is the complexity of tracing GLES applications for x86_64 on android.

**Comment by AWoloszyn** [comment] 2018-08-14 15:15
If your application is compiled in 32-bit mode, it should work. (Assuming it is possible to run a 32-bit x86 APK on x86_64 android).

**Comment by AWoloszyn** [comment] 2018-08-15 13:45
Since GLES has no concept of "layers" like Vulkan, our implementation to trace GLES calls on Android is basically as follows.

1) Connect to the application through the Java debugger (JDWP)
2) Pause the application
3) Load libgapii.so (System.LoadLibrary()) 
4) On load, libgapii.so patches all of the driver functions. Basically, writes a trampoline to call our functions, and and then we call through to the original driver.
   https://github.com/google/gapid/tree/master/gapii/interceptor-lib
5) I did not write this code originally, but it was my understanding that x86_64 is quite a bit wider than X86, and would require handling a lot more edge cases.

**Comment by AWoloszyn** [comment] 2018-08-15 13:46
Any help is always appreciated.

**Comment by tpalli** [comment] 2018-08-16 04:40
@AWoloszyn Thanks! I'll see if I can find someone with expertise on these things.

**Comment by pau-baiget** [comment] 2019-10-31 14:51
@tpalli were you able to try tracing on a recent (stable or developer) release? We will be closing this issue if we don't hear back soon. Thank you!

**Comment by tpalli** [comment] 2019-11-01 08:05
@pau-baiget I've tried gapid 1.6.1 and 1.7.0-dev-20191021, both of these are able to start a vulkan app (sascha willems demo) but both fail tracing with same expection failing to load /lib/x86_64/libgapii.so.

**Comment by pau-baiget** [comment] 2019-11-01 10:59
Thanks for the update @tpalli . We have several tickets opened with the same request, so we'll close this one as duplicate of https://github.com/google/gapid/issues/3138.

**Closed by pau-baiget** 2019-11-01 10:59 UTC
Labels: needs more information, triaged
