### ISSUE TITLE
GAPID fails at startup time on Windows 10

### ISSUE THREAD

**Issue by JessHolle** [google/gapid#3150] opened 2019-09-08 20:23 UTC
GAPID Version: 1.6.1:338bb67b0fe291f56f31d69f11ea1a45ed7cfeb6
OS: windows 10 amd64

installed the MSI, connected my Pixel (running Android 10) via USB (with latest adb, etc, installed and working fine), and tried to start gapid.exe.

And then I get:

com.google.gapid.Server$GapisInitException: Failed to connect to the graphics debugger
	at com.google.gapid.Server.connectToServer(Server.java:103)
	at com.google.gapid.Server.connect(Server.java:71)
	at com.google.gapid.Main$UI.startup(Main.java:135)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by JessHolle** [comment] 2019-09-08 20:25
Ah... it doesn't like *something* in my PATH as it starts if I put the gapid install directory at the start of y PATH.  Not exactly resilient nor is the error message helpful.

**Comment by hevrard** [comment] 2019-09-09 07:28
Thanks for reporting this issue,

It looks like you are using a build that you created yourself, can you tell us if you have the same issue with the latest stable release?
You can grab the windows build from: https://github.com/google/gapid/releases/tag/v1.6.1

**Comment by hevrard** [comment] 2019-09-09 07:30
Also, when your build fails to start, it should create gapis.log and gapic.log files under %TEMP%, can you upload those files here?

**Comment by JessHolle** [comment] 2019-09-09 12:06
I downloaded and installed https://github.com/google/gapid/releases/download/v1.6.1/gapid-1.6.1-windows.msi.

I just tried reproducing this issue -- and it worked without messing with PATH, so it's not 100% reproducible irrespective of PATH and PATH is likely a red herring.

Here are logs from the issue occurring, however.

[logs.zip](https://github.com/google/gapid/files/3590355/logs.zip)

**Comment by AWoloszyn** [comment] 2019-09-09 14:21
We have seen (on a VERY intermittent basis) that sometimes when you run GAPID on a windows machine it fails to start up. This is usually the first time you run GAPID, but might happen other times. We have not been able to come up with a repro case that lets us investigate easily.

**Comment by pau-baiget** [comment] 2019-10-09 13:33
Can https://github.com/google/gapid/issues/3201 be a duplicate of this issue?

**Comment by pau-baiget** [comment] 2019-10-09 13:35
@JessHolle have you observed this issue further?

**Comment by JessHolle** [comment] 2019-10-09 14:49
I have not attempted to use the tool since I reported the issue.

**Comment by pau-baiget** [comment] 2019-10-31 14:37
@JessHolle could you please try the latest developer release and let us know if you're able to reproduce the issue. If so, could you please update the gapi*.log files you'll find in the c:\temp directory? 

We'll keep this issue open for one more week to allow you providing more information. Thank you!!

**Comment by pau-baiget** [comment] 2020-01-09 11:57
@JessHolle we are closing this issue since it's been on hold waiting for more information for the last two months. Please re-open if you can provide more information, thank you!!

**Closed by pau-baiget** 2020-01-09 11:57 UTC
Labels: needs more information
