### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by silence-do-good** [google/gapid#3525] opened 2019-12-10 02:12 UTC
GAPID Version: 1.7.0:developer
OS: linux amd64

Took a Viking village trace for around 25 seconds and then opened it.

**Comment by silence-do-good** [comment] 2019-12-10 02:14
The error log:
Fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4f5e0ce]

runtime stack:
runtime.throw(0x66a2f97, 0x2a)
	GOROOT/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
	GOROOT/src/runtime/signal_unix.go:374 +0x4a9

goroutine 1259 [syscall]:
runtime.cgocall(0x4c4f827, 0xc000437810, 0xc00c000000)
	GOROOT/src/runtime/cgocall.go:128 +0x5b fp=0xc0004377e0 sp=0xc0004377a8 pc=0xaed71b
github.com/google/gapid/gapis/perfetto._Cfunc_parse_data(0x7f0814000e70, 0xc00c000000, 0x7f9da5b, 0x0)
	bazel-out/k8-fastbuild/bin/gapis/perfetto/linux_amd64_stripped/go_default_library%linux_amd64%cgo_codegen%/_cgo_gotypes.go:265 +0x4a fp=0xc000437810 sp=0xc0004377e0 pc=0x11d572a
github.com/google/gapid/gapis/perfetto.NewProcessor.func1(0x7f0814000e70, 0xc0004378f0, 0x6669e9b)
	processor.go:38 +0x11c fp=0xc000437860 sp=0xc000437810 pc=0x11d593c
github.com/google/gapid/gapis/perfetto.NewProcessor(0x70ac400, 0xc0016105a0, 0xc00c000000, 0x7f9da5b, 0x7fffe00, 0x7fffe00, 0x0, 0x0)
	processor.go:38 +0xc8 fp=0xc0004378e0 sp=0xc000437860 pc=0x11d50c8
github.com/google/gapid/gapis/capture.deserializePerfettoTrace(0x70ac400, 0xc0016105a0, 0xc00056f2c0, 0x6ed1320, 0xc00056f560, 0x0, 0x0, 0x0, 0x0)
	gapis/capture/perfetto.go:76 +0x163 fp=0xc000437948 sp=0xc0004378e0 pc=0x11e12b3
github.com/google/gapid/gapis/capture.fromProto(0x70ac400, 0xc0016105a0, 0xc00056f2c0, 0x0, 0x0, 0x0, 0x0)
	gapis/capture/capture.go:286 +0x464 fp=0xc000437a10 sp=0xc000437948 pc=0x11da324
github.com/google/gapid/gapis/capture.fromProtoWrapped(0x70ac400, 0xc0016104b0, 0xc00056f2c0, 0x0, 0x0, 0x0, 0x0)
	gapis/capture/capture.go:303 +0x3f fp=0xc000437a58 sp=0xc000437a10 pc=0x11da5ff
runtime.call64(0xc00052c3c0, 0x66f5818, 0xc0016c8f40, 0x1800000038)
	GOROOT/src/runtime/asm_amd64.s:520 +0x3b fp=0xc000437aa8 sp=0xc000437a58 pc=0xb459ab
reflect.Value.call(0x58e44c0, 0x66f5818, 0x13, 0x661c7dc, 0x4, 0xc00006be30, 0x2, 0x2, 0x0, 0xc7aa680, ...)
	GOROOT/src/reflect/value.go:447 +0x461 fp=0xc000437cc8 sp=0xc000437aa8 pc=0xb76e31
reflect.Value.Call(0x58e44c0, 0x66f5818, 0x13, 0xc0005bee30, 0x2, 0x2, 0x203000, 0xc0016104b0, 0xc0005beda8)
	GOROOT/src/reflect/value.go:308 +0xa4 fp=0xc000437d30 sp=0xc000437cc8 pc=0xb768b4
github.com/google/gapid/core/data/protoconv.ToObject(0x70ac400, 0xc0016104b0, 0x6fef280, 0xc00056f2c0, 0xc00056f2c0, 0xc0005bee01, 0xc001305080, 0xc000312370)
	core/data/protoconv/protoconv.go:156 +0x2c6 fp=0xc000437e70 sp=0xc000437d30 pc=0x1084486
github.com/google/gapid/gapis/database.(*record).resolve(0xc00056f320, 0x70ac400, 0xc0016104b0, 0x0, 0x0)
	gapis/database/memory.go:112 +0x302 fp=0xc000437f30 sp=0xc000437e70 pc=0x10912f2
github.com/google/gapid/gapis/database.(*memory).resolveLocked.func1()
	gapis/database/memory.go:241 +0x134 fp=0xc000437fb8 sp=0xc000437f30 pc=0x10934c4
github.com/google/gapid/core/app/crash.Go.func1(0xc001610450)
	core/app/crash/crash.go:65 +0x43 fp=0xc000437fd8 sp=0xc000437fb8 pc=0xc175a3
runtime.goexit()
	GOROOT/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000437fe0 sp=0xc000437fd8 pc=0xb47641
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 1 [select, 1 minutes]:
github.com/google/gapid/gapis/server.NewWithListener(0x70ac400, 0xc00026ff80, 0x6ff3c40, 0xc000568008, 0xc000610a80, 0xc00025ac08, 0x1, 0x1, 0x1, 0x7ffc97273043, ...)
	gapis/server/grpc.go:84 +0x3c6
github.com/google/gapid/gapis/server.Listen(0x70ac400, 0xc00026ff80, 0x6627e46, 0xb, 0xc000610a80, 0xc00025ac08, 0x1, 0x1, 0x1, 0x7ffc97273043, ...)
	gapis/server/grpc.go:50 +0xff
main.run(0x70ac400, 0xc00026ff80, 0xc000328340, 0x5)
	cmd/gapis/main.go:141 +0x764
github.com/google/gapid/core/app.doRun(0x66f61f8, 0x0)
	core/app/run.go:283 +0x3e3
github.com/google/gapid/core/app.Run(0x66f61f8)
	core/app/run.go:176 +0x2b
main.main()
	cmd/gapis/main.go:71 +0x75

goroutine 5 [syscall, 1 minutes]:
os/signal.signal_recv(0x0)
	GOROOT/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	GOROOT/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	GOROOT/src/os/signal/signal_unix.go:29 +0x41

goroutine 101 [select]:
github.com/google/gapid/core/app/analytics.(*batcher).run(0xc00002cfa0)
	core/app/analytics/batcher.go:67 +0x1ea
created by github.com/google/gapid/core/app/analytics.newBatcher
	core/app/analytics/batcher.go:40 +0xca

goroutine 16 [chan receive]:
github.com/google/gapid/core/log.Channel.func1()
	core/log/channel.go:30 +0xa7
github.com/google/gapid/core/app/crash.Go.func1(0xc0002e1080)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 130 [chan receive, 1 minutes]:
github.com/google/gapid/core/app.handleAbortSignals.func1()
	core/app/atexit.go:95 +0x69
github.com/google/gapid/core/app/crash.Go.func1(0xc00026ebd0)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 131 [chan receive, 1 minutes]:
github.com/google/gapid/core/app.AddCleanup.func1()
	core/app/atexit.go:59 +0x8b
github.com/google/gapid/core/app/crash.Go.func1(0xc00026f4a0)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 146 [select, 1 minutes]:
reflect.rselect(0xc0005b2040, 0x2, 0x2, 0xc0005b2040, 0xc0005606d8)
	GOROOT/src/runtime/select.go:542 +0x38d
reflect.Select(0xc0005609a0, 0x2, 0x64, 0xc00057a090, 0x0, 0x0, 0x0, 0x70ac400)
	GOROOT/src/reflect/value.go:2165 +0x171
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run(0xc000572000, 0x70ac400, 0xc000530090)
	gapis/replay/scheduler/scheduler.go:200 +0x7f0
github.com/google/gapid/gapis/replay/scheduler.New.func1()
	gapis/replay/scheduler/scheduler.go:78 +0x3c
github.com/google/gapid/core/app/crash.Go.func1(0xc00045ea00)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 74 [select, 1 minutes]:
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run.func2()
	gapis/replay/scheduler/scheduler.go:181 +0x340
github.com/google/gapid/core/app/crash.Go.func1(0xc0005b2000)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 162 [select]:
github.com/google/gapid/core/os/android/adb.Monitor(0x70ac400, 0xc00026ff80, 0xc00026ed20, 0xb2d05e00, 0x0, 0x0)
	core/os/android/adb/device.go:92 +0x2eb
main.monitorAndroidDevices(0x70ac400, 0xc00026ff80, 0xc00026ed20, 0xc0005be798)
	cmd/gapis/main.go:172 +0x79
main.run.func1()
	cmd/gapis/main.go:124 +0x63
github.com/google/gapid/core/app/crash.Go.func1(0xc0005b6000)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 211 [select, 1 minutes]:
github.com/google/gapid/gapis/server.(*server).GetLogStream(0xc00056a040, 0x70ac400, 0xc000487290, 0x6f93580, 0xc0005740f0, 0x0, 0x0)
	gapis/server/server.go:471 +0x26f
github.com/google/gapid/gapis/server.(*grpcServer).GetLogStream(0xc00056a080, 0xc00045eda0, 0x70c2480, 0xc0005740d0, 0x0, 0x0)
	gapis/server/grpc.go:553 +0x188
github.com/google/gapid/gapis/service._Gapid_GetLogStream_Handler(0x646ae80, 0xc00056a080, 0x70c0380, 0xc000496000, 0xd1343a0, 0xc000570200)
	bazel-out/k8-fastbuild/bin/gapis/service/linux_amd64_stripped/service_go_proto%/github.com/google/gapid/gapis/service/service.pb.go:9741 +0x10c
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0003a8480, 0x70db3e0, 0xc0003fde00, 0xc000570200, 0xc0005c40f0, 0xc7aa080, 0x0, 0x0, 0x0)
	external/org_golang_google_grpc/server.go:1175 +0xacd
google.golang.org/grpc.(*Server).handleStream(0xc0003a8480, 0x70db3e0, 0xc0003fde00, 0xc000570200, 0x0)
	external/org_golang_google_grpc/server.go:1254 +0xcbe
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0002f0240, 0xc0003a8480, 0x70db3e0, 0xc0003fde00, 0xc000570200)
	external/org_golang_google_grpc/server.go:690 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	external/org_golang_google_grpc/server.go:688 +0xa1

goroutine 195 [select]:
io.(*pipe).Read(0xc0005a6640, 0xc00055c000, 0x1000, 0x1000, 0xc0005cdcc8, 0x2, 0x0)
	GOROOT/src/io/pipe.go:50 +0xe7
io.(*PipeReader).Read(0xc0005b41c0, 0xc00055c000, 0x1000, 0x1000, 0x66f6ba0, 0xc2b0f2, 0xc0005cdd48)
	GOROOT/src/io/pipe.go:127 +0x4c
bufio.(*Reader).fill(0xc0005cdf50)
	GOROOT/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).ReadSlice(0xc0005cdf50, 0xc0005cde0a, 0xc27720, 0xc876a40, 0xc00027ec80, 0x6646747, 0x14)
	GOROOT/src/bufio/bufio.go:356 +0x3d
bufio.(*Reader).ReadBytes(0xc0005cdf50, 0xc00026ff0a, 0x6646747, 0x14, 0xc0005cded8, 0x1, 0x1)
	GOROOT/src/bufio/bufio.go:434 +0x70
bufio.(*Reader).ReadString(...)
	GOROOT/src/bufio/bufio.go:474
github.com/google/gapid/gapidapk.launchPerfettoProducerFromApk.func1()
	gapidapk/deviceinfo.go:183 +0x214
github.com/google/gapid/core/app/crash.Go.func1(0xc000600d80)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 196 [IO wait]:
internal/poll.runtime_pollWait(0x7f09caa9a878, 0x72, 0xffffffffffffffff)
	GOROOT/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc00060ec78, 0x72, 0x8001, 0x8000, 0xffffffffffffffff)
	GOROOT/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	GOROOT/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00060ec60, 0xc001646000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	GOROOT/src/internal/poll/fd_unix.go:169 +0x19b
os.(*File).read(...)
	GOROOT/src/os/file_unix.go:263
os.(*File).Read(0xc0005b41e8, 0xc001646000, 0x8000, 0x8000, 0x287, 0x0, 0x0)
	GOROOT/src/os/file.go:108 +0x70
io.copyBuffer(0x6ed4c20, 0xc0005b41c8, 0x6ed5120, 0xc0005b41e8, 0xc001646000, 0x8000, 0x8000, 0xc00062d9b0, 0xc000064788, 0xc0000647a8)
	GOROOT/src/io/io.go:402 +0x122
io.Copy(...)
	GOROOT/src/io/io.go:364
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	GOROOT/src/os/exec/exec.go:288 +0x63
os/exec.(*Cmd).Start.func1(0xc0005782c0, 0xc0005a8c20)
	GOROOT/src/os/exec/exec.go:409 +0x27
created by os/exec.(*Cmd).Start
	GOROOT/src/os/exec/exec.go:408 +0x58f

goroutine 165 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7f09caa9a7a8, 0x72, 0x0)
	GOROOT/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0005a4418, 0x72, 0x0, 0x0, 0x66204b0)
	GOROOT/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	GOROOT/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0005a4400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	GOROOT/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc0005a4400, 0xc0005b4101, 0x0, 0x0)
	GOROOT/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc000568008, 0xc00006ad28, 0xc00006ad30, 0x18)
	GOROOT/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc000568008, 0x66f5d00, 0xc0003a8480, 0x70da240, 0xc0005b4188)
	GOROOT/src/net/tcpsock.go:260 +0x48
google.golang.org/grpc.(*Server).Serve(0xc0003a8480, 0x6ff3c40, 0xc000568008, 0x0, 0x0)
	external/org_golang_google_grpc/server.go:561 +0x1e9
github.com/google/gapid/core/net/grpcutil.ServeWithListener(0x70ac340, 0xc00056a0c0, 0x6ff3c40, 0xc000568008, 0xc00026a380, 0xc0003b2f70, 0x1, 0x1, 0x0, 0x0)
	core/net/grpcutil/server.go:53 +0x2a5
github.com/google/gapid/gapis/server.NewWithListener.func2()
	gapis/server/grpc.go:66 +0x188
github.com/google/gapid/core/app/crash.Go.func1(0xc000268ea0)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 132 [select]:
github.com/google/gapid/gapis/server.(*grpcServer).stopIfIdle(0xc00056a080, 0x70ac340, 0xc00056a0c0, 0xc0003a8480, 0xdf8475800, 0xc000258170)
	gapis/server/grpc.go:143 +0x205
github.com/google/gapid/gapis/server.NewWithListener.func2.1.1()
	gapis/server/grpc.go:76 +0x57
github.com/google/gapid/core/app/crash.Go.func1(0xc000234880)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 188 [select, 1 minutes]:
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run.func2()
	gapis/replay/scheduler/scheduler.go:181 +0x340
github.com/google/gapid/core/app/crash.Go.func1(0xc0016c8700)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 107 [select, 1 minutes]:
github.com/google/gapid/gapidapk.launchPerfettoProducerFromApk(0x70ac400, 0xc00026ff80, 0x7121e60, 0xc00056c040, 0xc0005a8720, 0x1, 0xc0003b3fa8)
	gapidapk/deviceinfo.go:214 +0x5b8
github.com/google/gapid/gapidapk.fetchDeviceInfo.func1()
	gapidapk/deviceinfo.go:113 +0x61
github.com/google/gapid/core/app/crash.Go.func1(0xc000600420)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 197 [select, 1 minutes]:
github.com/google/gapid/core/os/shell.(*localProcess).Wait(0xc0005b41d0, 0x70ac400, 0xc00026ff80, 0xb16c6f, 0x0)
	core/os/shell/local.go:51 +0x115
github.com/google/gapid/gapidapk.launchPerfettoProducerFromApk.func2()
	gapidapk/deviceinfo.go:210 +0x4a
github.com/google/gapid/core/app/crash.Go.func1(0xc000600e70)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

goroutine 112 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc00059afc0, 0x1, 0x0, 0x0, 0x0, 0x0)
	external/org_golang_google_grpc/internal/transport/controlbuf.go:317 +0x104
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc00060e840, 0x0, 0x0)

**Comment by hevrard** [comment] 2019-12-16 10:40
Duplicate of #3541

**Closed by hevrard** 2019-12-16 10:40 UTC
Labels: duplicate
