### ISSUE TITLE
The gapis server has exited with an error code of: -42

### ISSUE THREAD

**Issue by RenfengLiu** [google/gapid#3201] opened 2019-09-30 16:07 UTC
GAPID Version: 1.7.0:developer
OS: windows 10 amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

Complied from the latest code (commit: f17c58e2a03baa9f88662918195056f05aa59eb7) on Windows. After compilation is done, open the gapid.exe and had the error. 
```
com.google.gapid.Server$GapisInitException: Failed to connect to the graphics debugger
	at com.google.gapid.Server.connectToServer(Server.java:103)
	at com.google.gapid.Server.connect(Server.java:71)
	at com.google.gapid.Main$UI.startup(Main.java:136)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by RenfengLiu** [comment] 2019-09-30 16:13
tried to open the application a few times and now it can be opened correctly. Not sure what happen here.

**Comment by pau-baiget** [comment] 2019-10-09 13:16
Thanks @RenfengLiu . Since it's a one-off, do you want to keep this bug open in case you can reproduce it again?

**Comment by srvasn** [comment] 2019-10-10 00:30
Facing the same problem on Ubuntu 16.04. GAPID version is stable (1.6).

**Comment by srvasn** [comment] 2019-10-10 01:28
In my case, the problem came from not having the latest GLIBC (GLIBCXX_3.4.22 in this case). This can be found by checking the generated log at `/tmp/gapic.log`

I solved it by getting the updating libstdc++6 using the below commands.

```
add-apt-repository ppa:ubuntu-toolchain-r/test -y
apt-get update
apt-get install libstdc++6
```

**Comment by natduca** [comment] 2019-10-15 20:37
Thanks for the two bug reports! @RenfengLiu since you couldn't repro a second time, we will close this bug. @srvasn since your bug report was against an old GAPID version, we'd like for you to check against the latest. If you still have issues, please open a fresh bug with clearer repro steps or logs --- if you have the problem, but don't give us ways to repro, it's super hard for us to take action on.

**Closed** 2019-10-15 23:19 UTC

**Comment by srvasn** [comment] 2019-10-16 05:15
@natduca it wasn't really a bug, more like a missing dependency.
