### ISSUE TITLE
Unhandled exception in the UI thread.

### ISSUE THREAD

**Issue by stcdalyc** [google/gapid#2828] opened 2019-06-11 10:29 UTC
GAPID Version: 1.5.0:b33134fa99c398ce81dffd642aa11ea53c660518
OS: windows 7 amd64

![image](https://user-images.githubusercontent.com/6738727/59264916-c32c4a00-8c76-11e9-8713-973fa9c19a9e.png)
When I click on the red box area in the picture above

org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.IllegalStateException: Querying children before loaded)
	at org.eclipse.swt.SWT.error(SWT.java:4595)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:188)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3933)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3564)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)
	at org.eclipse.jface.window.Window.open(Window.java:797)
	at com.google.gapid.Main$UI.show(Main.java:119)
	at com.google.gapid.Main.main(Main.java:68)
Caused by: java.lang.IllegalStateException: Querying children before loaded
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.google.gapid.models.ApiState$Node.getOrCreateChildren(ApiState.java:212)
	at com.google.gapid.models.ApiState$Node.getChildren(ApiState.java:207)
	at com.google.gapid.views.StateView$StateTree$1.getChildNodes(StateView.java:349)
	at com.google.gapid.views.StateView$StateTree$1.getChildNodes(StateView.java:341)
	at com.google.gapid.widgets.LinkifiedTree$ContentProvider.getChildren(LinkifiedTree.java:250)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getRawChildren(AbstractTreeViewer.java:1422)
	at org.eclipse.jface.viewers.TreeViewer.getRawChildren(TreeViewer.java:350)
	at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:903)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getSortedChildren(AbstractTreeViewer.java:621)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:815)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:604)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:766)
	at org.eclipse.jface.viewers.AbstractTreeViewer.setExpandedState(AbstractTreeViewer.java:2518)
	at com.google.gapid.widgets.LinkifiedTree.setExpandedState(LinkifiedTree.java:188)
	at com.google.gapid.views.StateView.setExpanded(StateView.java:281)
	at com.google.gapid.views.StateView$2.onUiThread(StateView.java:274)
	at com.google.gapid.views.StateView$2.onUiThread(StateView.java:264)
	at com.google.gapid.rpc.UiCallback.lambda$onFinish$0(UiCallback.java:46)
	at com.google.gapid.widgets.Widgets.ifNotDisposed(Widgets.java:119)
	at com.google.gapid.widgets.Widgets.lambda$scheduleIfNotDisposed$1(Widgets.java:147)
	at com.google.gapid.widgets.Widgets.lambda$schedule$0(Widgets.java:139)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	... 6 more

**Comment by pmuetschard** [comment] 2019-07-03 14:27
dupe of #2557

**Closed by pmuetschard** 2019-07-03 14:27 UTC
