### ISSUE TITLE
Unlock the screen before starting gapir

### ISSUE THREAD

**Issue by pmuetschard** [google/gapid#2809] opened 2019-06-04 20:51 UTC
Use the same tricks for unlocking the screen for tracing before starting gapir.

**Comment by hevrard** [comment] 2019-06-21 12:41
Duplicate of #2791 

I would like to keep this one as an opportunity for first-time contribution.

**Comment by hevrard** [comment] 2019-06-21 13:38
Closing as duplicate

**Closed by hevrard** 2019-06-21 13:38 UTC
Labels: duplicate
