### ISSUE TITLE
Error during replay: Shader 1 failed to compile

### ISSUE THREAD

**Issue by JamesMilneFilmlight** [google/gapid#1443] opened 2017-11-30 23:03 UTC
I've been attempting to use gapid 0.9.0 on macOS 10.12.6 to record a trace of my application running on a Kindle Fire 7 (7th gen) running FireOS 5.6.0.0, (which is based on Android 5.1.1.) My Mac has a Radeon Pro 460 4096 MB GPU, so I'm running Apple/AMD drivers.

My Android application currently uses Regal to convert legacy OpenGL to GLESv2, which works. 

When I attempt to replay my trace from the Kindle Fire, it fails to compile fairly simple shaders:

```
Error during replay: "Shader 1 failed to compile. Error:

Original source:
 1: #version 100
 2: // program number 1
 3: #define in attribute
 4: #define out varying
 5: #define FLAT  
 6: precision highp float;
 7: uniform mat4 rglModelViewMatrix;
 8: uniform mat4 rglProjectionMatrix;
 9: in vec4 rglVertex;
10: in vec4 rglColor;
11: FLAT out vec4 rglFrontColor;
12: void main() {
13:     gl_Position = rglProjectionMatrix * rglModelViewMatrix * rglVertex;
14:     rglFrontColor = rglColor;
15:     rglFrontColor = clamp( rglFrontColor, 0.0, 1.0 );
16: }
17:
Translated source:
1:
"
```

These shaders run on the device, and they are fine in glslangValidator. 

Any advice on where to prod to determine why gapid can't compile the shader?

**Comment by ben-clayton** [comment] 2017-11-30 23:34
Hi @JamesMilneFilmlight,

Thank you for your bug report. At first glance it does seem like that shader should compile okay. Even if it shouldn't, that's a hopeless error message that should be fixed. 

I'll see if I can reproduce the issue and get back to you. 

Cheers,
Ben

**Comment by JamesMilneFilmlight** [comment] 2017-12-01 09:35
Hi Ben, here's a trace which reproduces this issue:

https://drive.google.com/open?id=1KCprRKtCnVxW5NZwdZnjxc8iWOgXDpks

**Comment by ben-clayton** [comment] 2017-12-01 12:50
Thanks @JamesMilneFilmlight,

I can reproduce. I'm looking into it.

Cheers,
Ben

**Comment by ben-clayton** [comment] 2017-12-01 15:40
Hi @JamesMilneFilmlight,

I believe I have found and fixed the issue. However, it would seem that the font rendering is not rendering correctly during replay:

![filmlight](https://user-images.githubusercontent.com/11505236/33490084-d1fcd570-d6ad-11e7-8d9c-a37932083ba4.png)

Do you see the glyphs rendering correctly on the device? If so, I'll investigate further.

Cheers,
Ben

**Comment by JamesMilneFilmlight** [comment] 2017-12-01 15:45
No it doesn't, that's what I was trying to debug! 😁

**Comment by JamesMilneFilmlight** [comment] 2017-12-01 15:46
There are meant to be icons drawn to the left of the text on the buttons across the top, and an icon above the text on the large button in the centre though. Those do render on the device.

**Comment by ben-clayton** [comment] 2017-12-01 15:48
Great, thank you for the speedy reply.
Let me put the fixes up for review, once they've landed I can give you a custom build so you can continue your debugging :)

**Comment by ben-clayton** [comment] 2017-12-04 23:59
Hi @JamesMilneFilmlight,

Did you receive the build I sent you? If so, do you know if it fixes your issue?

Cheers,
Ben

**Comment by ben-clayton** [comment] 2018-03-13 18:30
Closing due to inactivity. @JamesMilneFilmlight - if you still see issues please open a new bug.

Many thanks,
Ben

**Closed by ben-clayton** 2018-03-13 18:30 UTC
Labels: GAPIS, GLES, P1
