### ISSUE TITLE
Exporting a texture does not respect the Flip Vertically flag

### ISSUE THREAD

**Issue by tomgoogle** [google/gapid#1218] opened 2017-10-18 01:09 UTC
When exporting a texture from the Textures pane, by default the texture will appear upside-down in the exported PNG. It should respect the Flip Vertically flag that is set at the time of exporting.

**Comment by pmuetschard** [comment] 2017-10-20 17:38
Dupe of #907

**Closed by pmuetschard** 2017-10-20 17:38 UTC
