### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by greatgoogleymoogley** [google/gapid#2273] opened 2018-10-05 21:11 UTC
GAPID Version: 1.1.0:874eed8e0372b54db789835e1ad36cb641e9fbea
OS: linux amd64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

Capturing an app that switches between inward and outward camera.

Capture Start
Switch camera
Capture stopped.

from other captures there are two textures with id 4, one of which is the texture used by an ImageView during app start to display a splash screen.
The ImageView is reused with a different texture when the camera is switched.
Capturing works fine before any camera switch.

```
panic: Can not find EGL image target: &{0x0000007412889eb0 1 0x00000073d95f4300 EGL_GL_TEXTURE_2D 10 EGLint(0x0@315)[3] <nil> {0xc449876358}} [recovered]
	panic: Panic at command 11762:glBindTexture(target: GL_TEXTURE_EXTERNAL_OES, texture: 4):
Can not find EGL image target: &{0x0000007412889eb0 1 0x00000073d95f4300 EGL_GL_TEXTURE_2D 10 EGLint(0x0@315)[3] <nil> {0xc449876358}} [recovered]
	panic: Panic at command 11762:glBindTexture(target: GL_TEXTURE_EXTERNAL_OES, texture: 4):
Can not find EGL image target: &{0x0000007412889eb0 1 0x00000073d95f4300 EGL_GL_TEXTURE_2D 10 EGLint(0x0@315)[3] <nil> {0xc449876358}}

goroutine 21 [running]:
github.com/google/gapid/core/app/crash.Crash(0x226e9e0, 0xc44de64c60)
	core/app/crash/crash.go:89 +0xa7
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x52
panic(0x226e9e0, 0xc44de64c60)
	GOROOT/src/runtime/panic.go:505 +0x229
github.com/google/gapid/gapis/api.ForeachCmd.func1(0xc4444ef858, 0xc4444ef880)
	gapis/api/cmd_foreach.go:39 +0x162
panic(0x226e9e0, 0xc44de64c50)
	GOROOT/src/runtime/panic.go:505 +0x229
github.com/google/gapid/gapis/api/gles.TextureId.remap(0xc400000004, 0x2ac7580, 0xc45671d920, 0xc449064600, 0x73f55a84f0, 0xc449060500, 0x400000de1)
	gapis/api/gles/custom_replay.go:92 +0x3ab
github.com/google/gapid/gapis/api/gles.(*GlBindTexture).Call(0xc45671d920, 0x2ab0a40, 0xc45671d8f0, 0xc449064600, 0xc449060500)
	bazel-out/k8-opt/genfiles/gapis/api/gles/mutate.go:41957 +0xa4
github.com/google/gapid/gapis/api/gles.(*GlBindTexture).Mutate(0xc45671d920, 0x2ab0a40, 0xc45671d8f0, 0x2df2, 0xc449064600, 0xc449060500, 0x0, 0x0)
	bazel-out/k8-opt/genfiles/gapis/api/gles/mutate.go:41945 +0x349
github.com/google/gapid/gapis/replay.(*adapter).MutateAndWrite(0xc442ff66d0, 0x2ab0a40, 0xc45671d8f0, 0x2df2, 0x2ac7580, 0xc45671d920)
	gapis/replay/batch.go:213 +0xcf
github.com/google/gapid/gapis/api/gles.(*destroyResourcesAtEOS).Transform(0x4a753a0, 0x2ab0a40, 0xc45671d8f0, 0x2df2, 0x2ac7580, 0xc45671d920, 0x2a7bf80, 0xc442ff66d0)
	gapis/api/gles/replay.go:295 +0x63
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc449064600, 0x2a7bb40, 0x4a753a0, 0x2a7bf80, 0xc442ff66d0, 0x2ab0a40, 0xc45671d8f0, 0x2df2, 0x2ac7580, 0xc45671d920)
	gapis/api/transform/transforms.go:98 +0x83
github.com/google/gapid/gapis/api/gles.compat.func3(0x2ab0a40, 0xc45671d8f0, 0x2df2, 0x2ac7580, 0xc4347ad890, 0x2a7df00, 0xc455783e00)
	gapis/api/gles/compat.go:295 +0xb8e2
github.com/google/gapid/gapis/api/transform.transform.Transform(0x286d66c, 0x6, 0xc4539f6b00, 0x2ab0a40, 0xc45671d8f0, 0x2df2, 0x2ac7580, 0xc4347ad890, 0x2a7df00, 0xc455783e00)
	gapis/api/transform/transforms.go:75 +0x75
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc449064600, 0x2a7df40, 0xc456efe120, 0x2a7df00, 0xc455783e00, 0x2ab0a40, 0xc45671d8f0, 0x2df2, 0x2ac7580, 0xc4347ad890)
	gapis/api/transform/transforms.go:98 +0x83
github.com/google/gapid/gapis/api/gles.undefinedFramebuffer.func1(0x2ab0a40, 0xc45671d8f0, 0x2df2, 0x2ac7580, 0xc4347ad890, 0x2a7df00, 0xc455783e30)
	gapis/api/gles/undefined_framebuffer.go:31 +0x9c
github.com/google/gapid/gapis/api/transform.transform.Transform(0x2879ca4, 0x10, 0xc456efe040, 0x2ab0a40, 0xc45671d8f0, 0x2df2, 0x2ac7580, 0xc4347ad890, 0x2a7df00, 0xc455783e30)
	gapis/api/transform/transforms.go:75 +0x75
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc449064600, 0x2a7df40, 0xc456efe060, 0x2a7df00, 0xc455783e30, 0x2ab0a40, 0xc45671d8f0, 0x2df2, 0x2ac7580, 0xc4347ad890)
	gapis/api/transform/transforms.go:98 +0x83
github.com/google/gapid/gapis/api/gles.(*findIssues).Transform(0xc4539699a0, 0x2ab0a40, 0xc45671d8f0, 0x2df2, 0x2ac7580, 0xc4347ad890, 0x2a7df00, 0xc455783e60)
	gapis/api/gles/find_issues.go:118 +0x1e6
github.com/google/gapid/gapis/api/transform.TransformWriter.MutateAndWrite(0xc449064600, 0x2a7bb80, 0xc4539699a0, 0x2a7df00, 0xc455783e60, 0x2ab0a40, 0xc456f22660, 0x2df2, 0x2ac7580, 0xc4347ad890)
	gapis/api/transform/transforms.go:98 +0x83
github.com/google/gapid/gapis/api/transform.(*DeadCodeElimination).Flush.func1(0x2ab0a40, 0xc456f22660, 0x2df2, 0x2ac7580, 0xc4347ad890, 0x0, 0x0)
	gapis/api/transform/dead_code_elimination.go:84 +0x7f
github.com/google/gapid/gapis/api.ForeachCmd(0x2ab0a40, 0xc44a21ade0, 0xc441b4a000, 0x3ce9, 0x4c00, 0xc4444ef910, 0x0, 0x0)
	gapis/api/cmd_foreach.go:46 +0x148
github.com/google/gapid/gapis/api/transform.(*DeadCodeElimination).Flush(0xc455777fc0, 0x2ab0a40, 0xc44a21ade0, 0x2a7df00, 0xc455783e90)
	gapis/api/transform/dead_code_elimination.go:83 +0x257
github.com/google/gapid/gapis/api/transform.Transforms.Transform(0xc4536ef100, 0x5, 0x8, 0x2ab0a40, 0xc44a21ade0, 0xc4203fdb38, 0x0, 0x0, 0x2a7bf80, 0xc442ff66d0)
	gapis/api/transform/transforms.go:44 +0x33c
github.com/google/gapid/gapis/api/gles.API.Replay(0x2ab0a40, 0xc44a21abd0, 0xc449078130, 0xc449078128, 0x2357d80, 0x4a753a0, 0xc44906ba40, 0x1, 0x1, 0x41b6100, ...)
	gapis/api/gles/replay.go:231 +0xda7
github.com/google/gapid/gapis/replay.(*Manager).execute.func1()
	gapis/replay/batch.go:149 +0x18b
github.com/google/gapid/core/app/benchmark.(*DurationCounter).Time(0xc420215750, 0xc4203fe0f8)
	core/app/benchmark/counter.go:163 +0x7d
github.com/google/gapid/gapis/replay.(*Manager).execute(0xc4203c40c0, 0x2ab0a40, 0xc44a21abd0, 0x2a80ac0, 0xc4203b8130, 0x10dcdf12ac109c5d, 0x6564c7e34b2f80d8, 0x5ecb77e682c7aca2, 0xa6618711840287c7, 0xd4e063f54a4a944d, ...)
	gapis/replay/batch.go:148 +0x964
github.com/google/gapid/gapis/replay.(*Manager).batch.func1(0x2a80ac0, 0xc4203b8130, 0xc4203fe458, 0x840287c75ecb77e6, 0x4a4a944da6618711, 0xac109c5dd4e063f5, 0x4b2f80d810dcdf12, 0x82c7aca26564c7e3, 0x2357d80, 0x4a753a0, ...)
	gapis/replay/batch.go:83 +0x444
github.com/google/gapid/gapis/replay.(*Manager).batch(0xc4203c40c0, 0x2ab0a40, 0xc44a21a9c0, 0xc44906ba20, 0x1, 0x1, 0x2575640, 0x2a63138, 0x25b6e80, 0xc449a157c0, ...)
	gapis/replay/batch.go:84 +0x2d4
github.com/google/gapid/gapis/replay.(*Manager).(github.com/google/gapid/gapis/replay.batch)-fm(0x2ab0a40, 0xc4203ae840, 0xc44906ba20, 0x1, 0x1, 0x2575640, 0x2a63138, 0x25b6e80, 0xc449a157c0, 0x0)
	gapis/replay/manager.go:126 +0x93
github.com/google/gapid/gapis/replay/scheduler.(*bin).exec(0xc449893580, 0x2ab0a40, 0xc4203ae840, 0xc4203b8160)
	gapis/replay/scheduler/scheduler.go:243 +0x26d
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run(0xc4203c43e0, 0x2ab0a40, 0xc4203ae840)
	gapis/replay/scheduler/scheduler.go:176 +0x370
github.com/google/gapid/gapis/replay/scheduler.New.func1()
	gapis/replay/scheduler/scheduler.go:73 +0x3c
github.com/google/gapid/core/app/crash.Go.func1(0xc4203c4400)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f
```

**Comment by ben-clayton** [comment] 2018-10-09 09:03
Discussing via email.

**Comment by pmuetschard** [comment] 2018-10-17 18:52
This is a dupe of #2279

**Closed by pmuetschard** 2018-10-17 18:52 UTC
