### ISSUE TITLE
Cannot find -lkhronos

### ISSUE THREAD

**Issue by tE3rDA77Sr4WdyTH** [google/gapid#279] opened 2017-04-19 05:13 UTC
When building i get this error:
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lkhronos

**Comment by AWoloszyn** [comment] 2017-04-19 13:05
I think this is a duplicate of #222.
If you delete the submodules in third_party then call git submodule update --init that should fix your build issues.

If that still does not work, delete the contents of the build directory, and build from scratch.

Let me know if you still have problems building after this.

**Comment by tE3rDA77Sr4WdyTH** [comment] 2017-04-19 15:03
I tried the steps described, but it still doesnt work:

[206/557] Linking Go executable test/test-test-integration-service
FAILED: : && "/usr/bin/cmake" -DGO_ENV=/home/lukas/gapid/release/go/goenv.cmake -DBUILDBOT=OFF -DGO_BUILD=test/test-test-integration-service -DGO_PACKAGE=github.com/google/gapid/test/integration/service -P /home/lukas/go/src/github.com/google/gapid/cmake/Modules/GoCompile.cmake && :
\#  github.com/google/gapid/gapis/shadertools
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lkhronos
collect2: error: ld returned 1 exit status
CMake Error at /home/lukas/go/src/github.com/google/gapid/cmake/Modules/GoCompile.cmake:37 (message):
  2


[206/557] Building CXX object CMakeFiles/gapir_static.dir/gapir/cc/gles_gfx_api.cpp.o
ninja: build stopped: subcommand failed.
Error running /usr/bin/ninja [install]: Process returned error
   Cause: exit status 1
exit status 1

**Comment by pmuetschard** [comment] 2017-04-19 17:01
I think this is due to some implicit build dependency. IIUC, it's because of a cgo #-directive.
A workaround for now is to run ```./do build khronos``` followed by ```./do build```

**Comment by ben-clayton** [comment] 2017-04-19 17:11
I think you might be right @pmuetschard - there appears to be a missing `cgo_dependency(khronos)` line in [`CMakeBuild.cmake`](https://github.com/google/gapid/blob/master/gapis/shadertools/CMakeBuild.cmake)

**Closed** 2017-04-20 17:31 UTC
Labels: bug, build, P2
