### ISSUE TITLE
Clicking on "View Text" of Shader.Source in state does not show full shader

### ISSUE THREAD

**Issue by dsrbecky** [google/gapid#604] opened 2017-06-14 14:39 UTC
It is trimmed to only first couple of lines

**Comment by ben-clayton** [comment] 2017-06-20 09:27
Possibly fixed by https://github.com/google/gapid/commit/00a6138e0444dad65e60c07c682b11b39ee801bc?

**Comment by pmuetschard** [comment] 2017-06-20 09:47
Yes, this is a dupe of #422.

**Closed by pmuetschard** 2017-06-20 09:47 UTC
Labels: bug, GAPIC, P2, triaged
