### ISSUE TITLE
Texture are not captured on ARM Mali GPU 

### ISSUE THREAD

**Issue by ek9852** [google/gapid#477] opened 2017-05-31 21:56 UTC
Tested on Samsung S8 (Mali G71), texture are not captured, leading to corrupted rendered frame. 
Same program works in Qualcomm platform.
Not notice any abnormal log in Report or log or from console.

<img width="608" alt="bbb" src="https://cloud.githubusercontent.com/assets/6452203/26655706/c0b62e0c-4610-11e7-8a67-3841fbaf1bb1.png">

**Comment by ek9852** [comment] 2017-05-31 21:58
Pls notice that there are two version of Samsung S8, one is using Qualcomm 835, one is using Samsung Exynos. The problem one is using Samsung Exynos which using Mali GPU

**Comment by dsrbecky** [comment] 2017-05-31 22:43
Note that this can also be valid when caused by two things:
Your selected command is before the texture data was uploaded.
The texture is used as render-target - we currently do not show the content of those.
I assume it is not one of those cases by any chance?

**Comment by ek9852** [comment] 2017-05-31 22:59
@dsrbecky   it is not one of those cases.

**Comment by ben-clayton** [comment] 2017-06-01 08:48
@ek9852 - was there anything in logcat to suggest this is similar to https://github.com/google/gapid/issues/355, in that the function was unable to be traced?

**Comment by ek9852** [comment] 2017-06-01 17:07
@ben-clayton  You are correct. Both glTexImage2D and glTexSubImage2D are not intercepted
Log:
06-02 00:00:17.276 12235 12235 W GAPID   : installer.cpp:115 : Interceptor error: Intercepting function at 0xf166974c failed: Unhandled instruction:    sub     sp, sp, #92 (OpcodeId: 533)
06-02 00:00:17.276 12235 12235 E GAPID   : installer.cpp:171 : Couldn't intercept function glTexImage2D at 0xf166974c
06-02 00:00:17.530 12235 12235 W GAPID   : installer.cpp:115 : Interceptor error: Intercepting function at 0xf1669ae0 failed: End of function reached after 4 byte when rewriting 8 bytes
06-02 00:00:17.530 12235 12235 E GAPID   : installer.cpp:171 : Couldn't intercept function glVertexPointerBounds at 0xf1669ae0
06-02 00:00:17.556 12235 12235 W GAPID   : installer.cpp:115 : Interceptor error: Intercepting function at 0xf16690f0 failed: End of function reached after 4 byte when rewriting 8 bytes
06-02 00:00:17.556 12235 12235 E GAPID   : installer.cpp:171 : Couldn't intercept function glColorPointerBounds at 0xf16690f0
06-02 00:00:17.635 12235 12235 W GAPID   : installer.cpp:115 : Interceptor error: Intercepting function at 0xf070b044 failed: Unhandled instruction:    sub     sp, sp, #92 (OpcodeId: 533)
06-02 00:00:17.635 12235 12235 E GAPID   : installer.cpp:171 : Couldn't intercept function glTexImage2D at 0xf070b044
06-02 00:00:17.647 12235 12235 W GAPID   : installer.cpp:115 : Interceptor error: Intercepting function at 0xf1669954 failed: Unhandled instruction:    sub     sp, sp, #92 (OpcodeId: 533)
06-02 00:00:17.647 12235 12235 E GAPID   : installer.cpp:171 : Couldn't intercept function glTexSubImage2D at 0xf1669954

**Comment by ek9852** [comment] 2017-06-01 17:08
But this time we get another error for unhandled instruction : sub sp, sp, #92

**Comment by ben-clayton** [comment] 2017-06-12 17:34
Fixed by 7fb2e8d

**Closed by ben-clayton** 2017-06-12 17:34 UTC
Labels: GAPIS, GLES, P1
