### ISSUE TITLE
Unhandled exception in the UI thread.

### ISSUE THREAD

**Issue by Beelkic** [google/gapid#3322] opened 2019-10-29 06:40 UTC
GAPID Version: 1.7.0:dev-20191021-b198af2dc0ae304eb7531ad2e23ff570ae2ead9e
OS: mac os x x86_64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

**Comment by hevrard** [comment] 2019-11-04 10:38
@Beelkic could you check your logs to see if it is a duplicate of #3343 ?

**Comment by pau-baiget** [comment] 2019-12-09 11:41
Closing this ticket since it's been in "needs more information" for more than a month. @Beelkic please re-open if you're able to provide more information, thank you!

**Closed by pau-baiget** 2019-12-09 11:41 UTC
Labels: needs more information
