### ISSUE TITLE
The gapis server has exited with an error code of: 2

### ISSUE THREAD

**Issue by jnorberg-zynga** [google/gapid#2697] opened 2019-03-28 17:50 UTC
GAPID Version: 1.5.0:b33134fa99c398ce81dffd642aa11ea53c660518
OS: mac os x x86_64

Please provide detailed steps that led to the error and copy-paste the stack trace.
Extra details from the logs and the trace file would be extra helpful.

1. trying to open a trace-file

2. stack

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x44ec5a6]

goroutine 68 [running]:
github.com/google/gapid/core/app/crash.Crash(0x8381100, 0xdeb6a80)
	core/app/crash/crash.go:89 +0xa7
github.com/google/gapid/core/app/crash.handler()
	core/app/crash/crash.go:56 +0x52
panic(0x8381100, 0xdeb6a80)
	GOROOT/src/runtime/panic.go:513 +0x1b9
github.com/google/gapid/gapir/client.(*Connection).Shutdown(0x0, 0x93e93e0, 0xc00e9c67b0, 0x400dced, 0x8c0f3e0)
	gapir/client/connection.go:117 +0x26
github.com/google/gapid/gapir/client.(*session).close(0xc011a7a550, 0x93e93e0, 0xc00e9c67b0)
	gapir/client/session.go:377 +0x47
github.com/google/gapid/gapir/client.(*session).init(0xc011a7a550, 0x93e93e0, 0xc00e9c67b0, 0x9430840, 0xc0002226d0, 0xc00013e180, 0x0, 0x0, 0x0, 0x0, ...)
	gapir/client/session.go:80 +0x23b
github.com/google/gapid/gapir/client.(*Client).Connect(0xc00016a000, 0x93e93e0, 0xc00e9c67b0, 0x9430840, 0xc0002226d0, 0xc00013e180, 0x0, 0x0, 0x0)
	gapir/client/client.go:66 +0x276
github.com/google/gapid/gapis/replay.(*manager).connect(0xc00000c060, 0x93e93e0, 0xc00e9c66f0, 0x9430840, 0xc0002226d0, 0xc00013e180, 0x0, 0x0, 0x0)
	gapis/replay/replay_connection.go:205 +0x216
github.com/google/gapid/gapis/replay.(*manager).execute(0xc00000c060, 0x93e93e0, 0xc00e9c66f0, 0x9430840, 0xc0002226d0, 0x61b20efc7785d7ab, 0x73eca0407ccfb0d5, 0xc09c37121e146450, 0xac655032f6e3f16, 0x93854cb773941acc, ...)
	gapis/replay/batch.go:270 +0x85a
github.com/google/gapid/gapis/replay.(*manager).batch.func1(0x9430840, 0xc0002226d0, 0xc00058a460, 0x2f6e3f16c09c3712, 0x73941acc0ac65503, 0x7785d7ab93854cb7, 0x7ccfb0d561b20efc, 0x1e14645073eca040, 0x837e7c0, 0xdf2a3f8, ...)
	gapis/replay/batch.go:86 +0x41e
github.com/google/gapid/gapis/replay.(*manager).batch(0xc00000c060, 0x93e93e0, 0xc00e9c63c0, 0xc00f897f40, 0x1, 0x1, 0x88b0c20, 0x92ef018, 0x88dde80, 0xc01015cd20, ...)
	gapis/replay/batch.go:87 +0x440
github.com/google/gapid/gapis/replay.(*manager).batch-fm(0x93e93e0, 0xc000268120, 0xc00f897f40, 0x1, 0x1, 0x88b0c20, 0x92ef018, 0x88dde80, 0xc01015cd20, 0x0)
	gapis/replay/manager.go:146 +0x8d
github.com/google/gapid/gapis/replay/scheduler.(*bin).exec(0xc00d02c200, 0x93e93e0, 0xc000268120, 0xc00016a0d0)
	gapis/replay/scheduler/scheduler.go:247 +0x271
github.com/google/gapid/gapis/replay/scheduler.(*Scheduler).run(0xc00000c4e0, 0x93e93e0, 0xc000268120)
	gapis/replay/scheduler/scheduler.go:180 +0x439
github.com/google/gapid/gapis/replay/scheduler.New.func1()
	gapis/replay/scheduler/scheduler.go:74 +0x3c
github.com/google/gapid/core/app/crash.Go.func1(0xc00000c500)
	core/app/crash/crash.go:65 +0x43
created by github.com/google/gapid/core/app/crash.Go
	core/app/crash/crash.go:63 +0x3f

**Comment by AWoloszyn** [comment] 2019-03-28 20:06
This is a duplicate of https://github.com/google/gapid/issues/2620.
And fixed in https://github.com/google/gapid/pull/2669

**Closed by AWoloszyn** 2019-03-28 20:06 UTC
