### ISSUE TITLE
Tracing Failed   Cause: Could not start trace   Cause: Could not parse package: 'fm.qingting.customize.samsung.PlayService:'

### ISSUE THREAD

**Issue by RyderFL** [google/gapid#3836] opened 2020-08-24 04:53 UTC
GAPID Version: 1.6.1:338bb67b0fe291f56f31d69f11ea1a45ed7cfeb6
OS: windows 8.1 amd64

com.google.gapid.server.Client$InternalServerErrorException: Tracing Failed
   Cause: Could not start trace
   Cause: Could not parse package: 'fm.qingting.customize.samsung.PlayService:'

	at com.google.gapid.server.Client.throwIfError(Client.java:312)

	at com.google.gapid.server.Client.lambda$streamTrace$52(Client.java:286)

	at com.google.gapid.server.GapidClientGrpc$StreamHandler.onNext(GapidClientGrpc.java:224)

	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:421)

	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)

	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)

	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:519)

	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)

	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.lang.Thread.run(Thread.java:748)

Caused by: com.google.gapid.server.Client$Stack: For request: RPC->streamTrace()

	at com.google.gapid.server.Client.streamTrace(Client.java:283)

	at com.google.gapid.server.Tracer.trace(Tracer.java:41)

	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:149)

	at com.google.gapid.LoadingScreen.lambda$createOptions$0(LoadingScreen.java:114)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)

	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Widget.java:1096)

	at org.eclipse.swt.widgets.Link.WM_LBUTTONUP(Link.java:1014)

	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4805)

	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4784)

	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)

	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2309)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3559)

	at org.eclipse.jface.window.Window.runEventLoop(Window.java:821)

	at org.eclipse.jface.window.Window.open(Window.java:797)

	at com.google.gapid.Main$UI.show(Main.java:119)

	at com.google.gapid.Main.main(Main.java:68)

**Comment by pmuetschard** [comment] 2020-08-31 16:59
This is a duplicate of #3841. Can you please provide the information requested there?

**Closed by pmuetschard** 2020-08-31 16:59 UTC
