### ISSUE TITLE
Does it support to x86 64-bit?

### ISSUE THREAD

**Issue by laxman1224** [google/gapid#2155] opened 2018-08-22 12:45 UTC
Hi,
Could you please confirm that gapid support to x86 64-bit?

**Comment by laxman1224** [comment] 2018-08-22 14:21
Thank you for the quick revert. Do you have any idea when does it support if it is under development or any future plan?

**Comment by pau-baiget** [comment] 2019-11-01 10:58
Closing as duplicate of https://github.com/google/gapid/issues/3138. We'll track the work required there.

**Closed by pau-baiget** 2019-11-01 10:58 UTC
Labels: triaged
