### ISSUE TITLE
GLES Shader attachments must be preserved when doing MEC

### ISSUE THREAD

**Issue by pau-baiget** [google/gapid#2728] opened 2019-04-24 11:42 UTC
Some apps destroy shaders after they've been attached to a program. A Mid-Execution Capture of these apps (starting after the shaders have been attached) doesn't currently store those shaders and therefore can't be modified (and pushed).

**Comment by AWoloszyn** [comment] 2019-04-25 17:37
I thought I remembered @pmuetschard  already fixing this.

**Comment by pmuetschard** [comment] 2019-05-16 21:09
Dupe of #398

**Closed by pmuetschard** 2019-05-16 21:09 UTC
Labels: GLES, enhancement
